// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapigen

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for BreakdownTraceScope.
const (
	BreakdownTraceScopeSentence BreakdownTraceScope = "sentence"
	BreakdownTraceScopeWord     BreakdownTraceScope = "word"
)

// Valid indicates whether the value is a known member of the BreakdownTraceScope enum.
func (e BreakdownTraceScope) Valid() bool {
	switch e {
	case BreakdownTraceScopeSentence:
		return true
	case BreakdownTraceScopeWord:
		return true
	default:
		return false
	}
}

// Defines values for BreakdownTraceSource.
const (
	BreakdownTraceSourceCache BreakdownTraceSource = "cache"
	BreakdownTraceSourceLLM   BreakdownTraceSource = "llm"
)

// Valid indicates whether the value is a known member of the BreakdownTraceSource enum.
func (e BreakdownTraceSource) Valid() bool {
	switch e {
	case BreakdownTraceSourceCache:
		return true
	case BreakdownTraceSourceLLM:
		return true
	default:
		return false
	}
}

// Defines values for ConversationStatus.
const (
	ConversationStatusActive   ConversationStatus = "active"
	ConversationStatusComplete ConversationStatus = "complete"
)

// Valid indicates whether the value is a known member of the ConversationStatus enum.
func (e ConversationStatus) Valid() bool {
	switch e {
	case ConversationStatusActive:
		return true
	case ConversationStatusComplete:
		return true
	default:
		return false
	}
}

// Defines values for ConversationTurnAction.
const (
	ConversationActionContinueStory ConversationTurnAction = "continue_story"
	ConversationActionDescend       ConversationTurnAction = "descend"
	ConversationActionRetryParent   ConversationTurnAction = "retry_parent"
)

// Valid indicates whether the value is a known member of the ConversationTurnAction enum.
func (e ConversationTurnAction) Valid() bool {
	switch e {
	case ConversationActionContinueStory:
		return true
	case ConversationActionDescend:
		return true
	case ConversationActionRetryParent:
		return true
	default:
		return false
	}
}

// Defines values for ConversationTurnAssessment.
const (
	ConversationAssessmentNotUnderstood ConversationTurnAssessment = "not_understood"
	ConversationAssessmentPartial       ConversationTurnAssessment = "partial"
	ConversationAssessmentUnderstood    ConversationTurnAssessment = "understood"
)

// Valid indicates whether the value is a known member of the ConversationTurnAssessment enum.
func (e ConversationTurnAssessment) Valid() bool {
	switch e {
	case ConversationAssessmentNotUnderstood:
		return true
	case ConversationAssessmentPartial:
		return true
	case ConversationAssessmentUnderstood:
		return true
	default:
		return false
	}
}

// Defines values for ConversationTurnKind.
const (
	ConversationKindLearnerResponse ConversationTurnKind = "learner_response"
	ConversationKindRepairStory     ConversationTurnKind = "repair_story"
	ConversationKindRetry           ConversationTurnKind = "retry"
	ConversationKindStory           ConversationTurnKind = "story"
)

// Valid indicates whether the value is a known member of the ConversationTurnKind enum.
func (e ConversationTurnKind) Valid() bool {
	switch e {
	case ConversationKindLearnerResponse:
		return true
	case ConversationKindRepairStory:
		return true
	case ConversationKindRetry:
		return true
	case ConversationKindStory:
		return true
	default:
		return false
	}
}

// Defines values for ConversationTurnRole.
const (
	ConversationRoleAssistant ConversationTurnRole = "assistant"
	ConversationRoleUser      ConversationTurnRole = "user"
)

// Valid indicates whether the value is a known member of the ConversationTurnRole enum.
func (e ConversationTurnRole) Valid() bool {
	switch e {
	case ConversationRoleAssistant:
		return true
	case ConversationRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionSource.
const (
	DefinitionSourceGlossary             DefinitionSource = "glossary"
	DefinitionSourceLlm                  DefinitionSource = "llm"
	DefinitionSourceMetadata             DefinitionSource = "metadata"
	DefinitionSourceUser                 DefinitionSource = "user"
	DefinitionSourceWiktionary           DefinitionSource = "wiktionary"
	DefinitionSourceWiktionaryNative     DefinitionSource = "wiktionary-native"
	DefinitionSourceWiktionaryTranslated DefinitionSource = "wiktionary-translated"
)

// Valid indicates whether the value is a known member of the DefinitionSource enum.
func (e DefinitionSource) Valid() bool {
	switch e {
	case DefinitionSourceGlossary:
		return true
	case DefinitionSourceLlm:
		return true
	case DefinitionSourceMetadata:
		return true
	case DefinitionSourceUser:
		return true
	case DefinitionSourceWiktionary:
		return true
	case DefinitionSourceWiktionaryNative:
		return true
	case DefinitionSourceWiktionaryTranslated:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionOptionSource.
const (
	DefinitionOptionSourceGlossary             DefinitionOptionSource = "glossary"
	DefinitionOptionSourceLlm                  DefinitionOptionSource = "llm"
	DefinitionOptionSourceMetadata             DefinitionOptionSource = "metadata"
	DefinitionOptionSourceUser                 DefinitionOptionSource = "user"
	DefinitionOptionSourceWiktionary           DefinitionOptionSource = "wiktionary"
	DefinitionOptionSourceWiktionaryNative     DefinitionOptionSource = "wiktionary-native"
	DefinitionOptionSourceWiktionaryTranslated DefinitionOptionSource = "wiktionary-translated"
)

// Valid indicates whether the value is a known member of the DefinitionOptionSource enum.
func (e DefinitionOptionSource) Valid() bool {
	switch e {
	case DefinitionOptionSourceGlossary:
		return true
	case DefinitionOptionSourceLlm:
		return true
	case DefinitionOptionSourceMetadata:
		return true
	case DefinitionOptionSourceUser:
		return true
	case DefinitionOptionSourceWiktionary:
		return true
	case DefinitionOptionSourceWiktionaryNative:
		return true
	case DefinitionOptionSourceWiktionaryTranslated:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceWinningSource.
const (
	DefinitionTraceWinningSourceGlossary             DefinitionTraceWinningSource = "glossary"
	DefinitionTraceWinningSourceLlm                  DefinitionTraceWinningSource = "llm"
	DefinitionTraceWinningSourceMetadata             DefinitionTraceWinningSource = "metadata"
	DefinitionTraceWinningSourceUser                 DefinitionTraceWinningSource = "user"
	DefinitionTraceWinningSourceWiktionary           DefinitionTraceWinningSource = "wiktionary"
	DefinitionTraceWinningSourceWiktionaryNative     DefinitionTraceWinningSource = "wiktionary-native"
	DefinitionTraceWinningSourceWiktionaryTranslated DefinitionTraceWinningSource = "wiktionary-translated"
)

// Valid indicates whether the value is a known member of the DefinitionTraceWinningSource enum.
func (e DefinitionTraceWinningSource) Valid() bool {
	switch e {
	case DefinitionTraceWinningSourceGlossary:
		return true
	case DefinitionTraceWinningSourceLlm:
		return true
	case DefinitionTraceWinningSourceMetadata:
		return true
	case DefinitionTraceWinningSourceUser:
		return true
	case DefinitionTraceWinningSourceWiktionary:
		return true
	case DefinitionTraceWinningSourceWiktionaryNative:
		return true
	case DefinitionTraceWinningSourceWiktionaryTranslated:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceStepSource.
const (
	DefinitionTraceStepSourceGlossary             DefinitionTraceStepSource = "glossary"
	DefinitionTraceStepSourceLlm                  DefinitionTraceStepSource = "llm"
	DefinitionTraceStepSourceMetadata             DefinitionTraceStepSource = "metadata"
	DefinitionTraceStepSourceUser                 DefinitionTraceStepSource = "user"
	DefinitionTraceStepSourceWiktionary           DefinitionTraceStepSource = "wiktionary"
	DefinitionTraceStepSourceWiktionaryNative     DefinitionTraceStepSource = "wiktionary-native"
	DefinitionTraceStepSourceWiktionaryTranslated DefinitionTraceStepSource = "wiktionary-translated"
)

// Valid indicates whether the value is a known member of the DefinitionTraceStepSource enum.
func (e DefinitionTraceStepSource) Valid() bool {
	switch e {
	case DefinitionTraceStepSourceGlossary:
		return true
	case DefinitionTraceStepSourceLlm:
		return true
	case DefinitionTraceStepSourceMetadata:
		return true
	case DefinitionTraceStepSourceUser:
		return true
	case DefinitionTraceStepSourceWiktionary:
		return true
	case DefinitionTraceStepSourceWiktionaryNative:
		return true
	case DefinitionTraceStepSourceWiktionaryTranslated:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceStepStatus.
const (
	Hit     DefinitionTraceStepStatus = "hit"
	Miss    DefinitionTraceStepStatus = "miss"
	Skipped DefinitionTraceStepStatus = "skipped"
)

// Valid indicates whether the value is a known member of the DefinitionTraceStepStatus enum.
func (e DefinitionTraceStepStatus) Valid() bool {
	switch e {
	case Hit:
		return true
	case Miss:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceStepStep.
const (
	CanonicalKeyFollow DefinitionTraceStepStep = "canonical_key_follow"
	KnowledgeMetadata  DefinitionTraceStepStep = "knowledge_metadata"
	LlmFallback        DefinitionTraceStepStep = "llm_fallback"
	SharedCache        DefinitionTraceStepStep = "shared_cache"
	StoryGlossary      DefinitionTraceStepStep = "story_glossary"
	UserDictionary     DefinitionTraceStepStep = "user_dictionary"
	Wiktionary         DefinitionTraceStepStep = "wiktionary"
)

// Valid indicates whether the value is a known member of the DefinitionTraceStepStep enum.
func (e DefinitionTraceStepStep) Valid() bool {
	switch e {
	case CanonicalKeyFollow:
		return true
	case KnowledgeMetadata:
		return true
	case LlmFallback:
		return true
	case SharedCache:
		return true
	case StoryGlossary:
		return true
	case UserDictionary:
		return true
	case Wiktionary:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestExpressionOutput.
const (
	GenerateRequestExpressionOutputPhrases GenerateRequestExpressionOutput = "phrases"
	GenerateRequestExpressionOutputStory   GenerateRequestExpressionOutput = "story"
)

// Valid indicates whether the value is a known member of the GenerateRequestExpressionOutput enum.
func (e GenerateRequestExpressionOutput) Valid() bool {
	switch e {
	case GenerateRequestExpressionOutputPhrases:
		return true
	case GenerateRequestExpressionOutputStory:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestSessionType.
const (
	GenerateRequestSessionTypeExpressionGuided GenerateRequestSessionType = "expression_guided"
	GenerateRequestSessionTypeSystem           GenerateRequestSessionType = "system"
	GenerateRequestSessionTypeTopicGuided      GenerateRequestSessionType = "topic_guided"
)

// Valid indicates whether the value is a known member of the GenerateRequestSessionType enum.
func (e GenerateRequestSessionType) Valid() bool {
	switch e {
	case GenerateRequestSessionTypeExpressionGuided:
		return true
	case GenerateRequestSessionTypeSystem:
		return true
	case GenerateRequestSessionTypeTopicGuided:
		return true
	default:
		return false
	}
}

// Defines values for GenerationEventContentType.
const (
	GenerationEventContentTypePhraseSet GenerationEventContentType = "phrase_set"
	GenerationEventContentTypeStory     GenerationEventContentType = "story"
)

// Valid indicates whether the value is a known member of the GenerationEventContentType enum.
func (e GenerationEventContentType) Valid() bool {
	switch e {
	case GenerationEventContentTypePhraseSet:
		return true
	case GenerationEventContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for GenerationEventStatus.
const (
	GenerationEventStatusComplete   GenerationEventStatus = "complete"
	GenerationEventStatusFailed     GenerationEventStatus = "failed"
	GenerationEventStatusGenerating GenerationEventStatus = "generating"
	GenerationEventStatusInProgress GenerationEventStatus = "in_progress"
	GenerationEventStatusPending    GenerationEventStatus = "pending"
	GenerationEventStatusReading    GenerationEventStatus = "reading"
	GenerationEventStatusReady      GenerationEventStatus = "ready"
)

// Valid indicates whether the value is a known member of the GenerationEventStatus enum.
func (e GenerationEventStatus) Valid() bool {
	switch e {
	case GenerationEventStatusComplete:
		return true
	case GenerationEventStatusFailed:
		return true
	case GenerationEventStatusGenerating:
		return true
	case GenerationEventStatusInProgress:
		return true
	case GenerationEventStatusPending:
		return true
	case GenerationEventStatusReading:
		return true
	case GenerationEventStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStageRecordStatus.
const (
	GenerationStageRecordStatusComplete   GenerationStageRecordStatus = "complete"
	GenerationStageRecordStatusFailed     GenerationStageRecordStatus = "failed"
	GenerationStageRecordStatusInProgress GenerationStageRecordStatus = "in_progress"
	GenerationStageRecordStatusPending    GenerationStageRecordStatus = "pending"
)

// Valid indicates whether the value is a known member of the GenerationStageRecordStatus enum.
func (e GenerationStageRecordStatus) Valid() bool {
	switch e {
	case GenerationStageRecordStatusComplete:
		return true
	case GenerationStageRecordStatusFailed:
		return true
	case GenerationStageRecordStatusInProgress:
		return true
	case GenerationStageRecordStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for GradeGradedBy.
const (
	Llm  GradeGradedBy = "llm"
	Rule GradeGradedBy = "rule"
)

// Valid indicates whether the value is a known member of the GradeGradedBy enum.
func (e GradeGradedBy) Valid() bool {
	switch e {
	case Llm:
		return true
	case Rule:
		return true
	default:
		return false
	}
}

// Defines values for LLMCallStatus.
const (
	LLMCallStatusError   LLMCallStatus = "error"
	LLMCallStatusSuccess LLMCallStatus = "success"
	LLMCallStatusTimeout LLMCallStatus = "timeout"
)

// Valid indicates whether the value is a known member of the LLMCallStatus enum.
func (e LLMCallStatus) Valid() bool {
	switch e {
	case LLMCallStatusError:
		return true
	case LLMCallStatusSuccess:
		return true
	case LLMCallStatusTimeout:
		return true
	default:
		return false
	}
}

// Defines values for LLMCallLogRowStatus.
const (
	LLMCallLogRowStatusError   LLMCallLogRowStatus = "error"
	LLMCallLogRowStatusSuccess LLMCallLogRowStatus = "success"
	LLMCallLogRowStatusTimeout LLMCallLogRowStatus = "timeout"
)

// Valid indicates whether the value is a known member of the LLMCallLogRowStatus enum.
func (e LLMCallLogRowStatus) Valid() bool {
	switch e {
	case LLMCallLogRowStatusError:
		return true
	case LLMCallLogRowStatusSuccess:
		return true
	case LLMCallLogRowStatusTimeout:
		return true
	default:
		return false
	}
}

// Defines values for LanguageKeyStrategy.
const (
	Lemma   LanguageKeyStrategy = "lemma"
	Root    LanguageKeyStrategy = "root"
	Stem    LanguageKeyStrategy = "stem"
	Surface LanguageKeyStrategy = "surface"
)

// Valid indicates whether the value is a known member of the LanguageKeyStrategy enum.
func (e LanguageKeyStrategy) Valid() bool {
	switch e {
	case Lemma:
		return true
	case Root:
		return true
	case Stem:
		return true
	case Surface:
		return true
	default:
		return false
	}
}

// Defines values for ProfileLevel.
const (
	ProfileLevelAdvanced          ProfileLevel = "advanced"
	ProfileLevelBeginner          ProfileLevel = "beginner"
	ProfileLevelElementary        ProfileLevel = "elementary"
	ProfileLevelIntermediate      ProfileLevel = "intermediate"
	ProfileLevelUpperIntermediate ProfileLevel = "upper-intermediate"
)

// Valid indicates whether the value is a known member of the ProfileLevel enum.
func (e ProfileLevel) Valid() bool {
	switch e {
	case ProfileLevelAdvanced:
		return true
	case ProfileLevelBeginner:
		return true
	case ProfileLevelElementary:
		return true
	case ProfileLevelIntermediate:
		return true
	case ProfileLevelUpperIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for ProfilePatchLevel.
const (
	ProfilePatchLevelAdvanced          ProfilePatchLevel = "advanced"
	ProfilePatchLevelBeginner          ProfilePatchLevel = "beginner"
	ProfilePatchLevelElementary        ProfilePatchLevel = "elementary"
	ProfilePatchLevelIntermediate      ProfilePatchLevel = "intermediate"
	ProfilePatchLevelUpperIntermediate ProfilePatchLevel = "upper-intermediate"
)

// Valid indicates whether the value is a known member of the ProfilePatchLevel enum.
func (e ProfilePatchLevel) Valid() bool {
	switch e {
	case ProfilePatchLevelAdvanced:
		return true
	case ProfilePatchLevelBeginner:
		return true
	case ProfilePatchLevelElementary:
		return true
	case ProfilePatchLevelIntermediate:
		return true
	case ProfilePatchLevelUpperIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for ReaderEventEventType.
const (
	Lookup            ReaderEventEventType = "lookup"
	Navigate          ReaderEventEventType = "navigate"
	NotReadyReadAgain ReaderEventEventType = "not_ready_read_again"
	Rate              ReaderEventEventType = "rate"
	ReferencePeek     ReaderEventEventType = "reference_peek"
	SentenceBreak     ReaderEventEventType = "sentence_break"
)

// Valid indicates whether the value is a known member of the ReaderEventEventType enum.
func (e ReaderEventEventType) Valid() bool {
	switch e {
	case Lookup:
		return true
	case Navigate:
		return true
	case NotReadyReadAgain:
		return true
	case Rate:
		return true
	case ReferencePeek:
		return true
	case SentenceBreak:
		return true
	default:
		return false
	}
}

// Defines values for ReaderKnowledgeLevel.
const (
	ReaderKnowledgeLevelEmpty     ReaderKnowledgeLevel = ""
	ReaderKnowledgeLevelIgnored   ReaderKnowledgeLevel = "ignored"
	ReaderKnowledgeLevelN1        ReaderKnowledgeLevel = "1"
	ReaderKnowledgeLevelN2        ReaderKnowledgeLevel = "2"
	ReaderKnowledgeLevelN3        ReaderKnowledgeLevel = "3"
	ReaderKnowledgeLevelN4        ReaderKnowledgeLevel = "4"
	ReaderKnowledgeLevelN5        ReaderKnowledgeLevel = "5"
	ReaderKnowledgeLevelWellKnown ReaderKnowledgeLevel = "well_known"
)

// Valid indicates whether the value is a known member of the ReaderKnowledgeLevel enum.
func (e ReaderKnowledgeLevel) Valid() bool {
	switch e {
	case ReaderKnowledgeLevelEmpty:
		return true
	case ReaderKnowledgeLevelIgnored:
		return true
	case ReaderKnowledgeLevelN1:
		return true
	case ReaderKnowledgeLevelN2:
		return true
	case ReaderKnowledgeLevelN3:
		return true
	case ReaderKnowledgeLevelN4:
		return true
	case ReaderKnowledgeLevelN5:
		return true
	case ReaderKnowledgeLevelWellKnown:
		return true
	default:
		return false
	}
}

// Defines values for ReaderSurfaceKnowledgeLevel.
const (
	ReaderSurfaceKnowledgeLevelEmpty     ReaderSurfaceKnowledgeLevel = ""
	ReaderSurfaceKnowledgeLevelIgnored   ReaderSurfaceKnowledgeLevel = "ignored"
	ReaderSurfaceKnowledgeLevelN1        ReaderSurfaceKnowledgeLevel = "1"
	ReaderSurfaceKnowledgeLevelN2        ReaderSurfaceKnowledgeLevel = "2"
	ReaderSurfaceKnowledgeLevelN3        ReaderSurfaceKnowledgeLevel = "3"
	ReaderSurfaceKnowledgeLevelN4        ReaderSurfaceKnowledgeLevel = "4"
	ReaderSurfaceKnowledgeLevelN5        ReaderSurfaceKnowledgeLevel = "5"
	ReaderSurfaceKnowledgeLevelWellKnown ReaderSurfaceKnowledgeLevel = "well_known"
)

// Valid indicates whether the value is a known member of the ReaderSurfaceKnowledgeLevel enum.
func (e ReaderSurfaceKnowledgeLevel) Valid() bool {
	switch e {
	case ReaderSurfaceKnowledgeLevelEmpty:
		return true
	case ReaderSurfaceKnowledgeLevelIgnored:
		return true
	case ReaderSurfaceKnowledgeLevelN1:
		return true
	case ReaderSurfaceKnowledgeLevelN2:
		return true
	case ReaderSurfaceKnowledgeLevelN3:
		return true
	case ReaderSurfaceKnowledgeLevelN4:
		return true
	case ReaderSurfaceKnowledgeLevelN5:
		return true
	case ReaderSurfaceKnowledgeLevelWellKnown:
		return true
	default:
		return false
	}
}

// Defines values for ReaderSurfaceKnowledgeRequestLevel.
const (
	ReaderSurfaceKnowledgeRequestLevelEmpty     ReaderSurfaceKnowledgeRequestLevel = ""
	ReaderSurfaceKnowledgeRequestLevelIgnored   ReaderSurfaceKnowledgeRequestLevel = "ignored"
	ReaderSurfaceKnowledgeRequestLevelN1        ReaderSurfaceKnowledgeRequestLevel = "1"
	ReaderSurfaceKnowledgeRequestLevelN2        ReaderSurfaceKnowledgeRequestLevel = "2"
	ReaderSurfaceKnowledgeRequestLevelN3        ReaderSurfaceKnowledgeRequestLevel = "3"
	ReaderSurfaceKnowledgeRequestLevelN4        ReaderSurfaceKnowledgeRequestLevel = "4"
	ReaderSurfaceKnowledgeRequestLevelN5        ReaderSurfaceKnowledgeRequestLevel = "5"
	ReaderSurfaceKnowledgeRequestLevelWellKnown ReaderSurfaceKnowledgeRequestLevel = "well_known"
)

// Valid indicates whether the value is a known member of the ReaderSurfaceKnowledgeRequestLevel enum.
func (e ReaderSurfaceKnowledgeRequestLevel) Valid() bool {
	switch e {
	case ReaderSurfaceKnowledgeRequestLevelEmpty:
		return true
	case ReaderSurfaceKnowledgeRequestLevelIgnored:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN1:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN2:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN3:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN4:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN5:
		return true
	case ReaderSurfaceKnowledgeRequestLevelWellKnown:
		return true
	default:
		return false
	}
}

// Defines values for ReaderTraceKind.
const (
	ReaderTraceKindDefinitionLookup  ReaderTraceKind = "definition_lookup"
	ReaderTraceKindSentenceBreakdown ReaderTraceKind = "sentence_breakdown"
	ReaderTraceKindWordBreakdown     ReaderTraceKind = "word_breakdown"
)

// Valid indicates whether the value is a known member of the ReaderTraceKind enum.
func (e ReaderTraceKind) Valid() bool {
	switch e {
	case ReaderTraceKindDefinitionLookup:
		return true
	case ReaderTraceKindSentenceBreakdown:
		return true
	case ReaderTraceKindWordBreakdown:
		return true
	default:
		return false
	}
}

// Defines values for ReaderTraceStatus.
const (
	ReaderTraceStatusHit     ReaderTraceStatus = "hit"
	ReaderTraceStatusMiss    ReaderTraceStatus = "miss"
	ReaderTraceStatusSkipped ReaderTraceStatus = "skipped"
)

// Valid indicates whether the value is a known member of the ReaderTraceStatus enum.
func (e ReaderTraceStatus) Valid() bool {
	switch e {
	case ReaderTraceStatusHit:
		return true
	case ReaderTraceStatusMiss:
		return true
	case ReaderTraceStatusSkipped:
		return true
	default:
		return false
	}
}

// Defines values for SentenceBreakdownTraceStructureHint.
const (
	SentenceBreakdownTraceStructureHintHit          SentenceBreakdownTraceStructureHint = "hit"
	SentenceBreakdownTraceStructureHintMiss         SentenceBreakdownTraceStructureHint = "miss"
	SentenceBreakdownTraceStructureHintNotConsulted SentenceBreakdownTraceStructureHint = "not_consulted"
)

// Valid indicates whether the value is a known member of the SentenceBreakdownTraceStructureHint enum.
func (e SentenceBreakdownTraceStructureHint) Valid() bool {
	switch e {
	case SentenceBreakdownTraceStructureHintHit:
		return true
	case SentenceBreakdownTraceStructureHintMiss:
		return true
	case SentenceBreakdownTraceStructureHintNotConsulted:
		return true
	default:
		return false
	}
}

// Defines values for SessionContentContentType.
const (
	SessionContentContentTypePhraseSet SessionContentContentType = "phrase_set"
	SessionContentContentTypeStory     SessionContentContentType = "story"
)

// Valid indicates whether the value is a known member of the SessionContentContentType enum.
func (e SessionContentContentType) Valid() bool {
	switch e {
	case SessionContentContentTypePhraseSet:
		return true
	case SessionContentContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailContentType.
const (
	SessionDetailContentTypePhraseSet SessionDetailContentType = "phrase_set"
	SessionDetailContentTypeStory     SessionDetailContentType = "story"
)

// Valid indicates whether the value is a known member of the SessionDetailContentType enum.
func (e SessionDetailContentType) Valid() bool {
	switch e {
	case SessionDetailContentTypePhraseSet:
		return true
	case SessionDetailContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailExpressionOutput.
const (
	SessionDetailExpressionOutputPhrases SessionDetailExpressionOutput = "phrases"
	SessionDetailExpressionOutputStory   SessionDetailExpressionOutput = "story"
)

// Valid indicates whether the value is a known member of the SessionDetailExpressionOutput enum.
func (e SessionDetailExpressionOutput) Valid() bool {
	switch e {
	case SessionDetailExpressionOutputPhrases:
		return true
	case SessionDetailExpressionOutputStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailSessionType.
const (
	SessionDetailSessionTypeExpressionGuided SessionDetailSessionType = "expression_guided"
	SessionDetailSessionTypeSystem           SessionDetailSessionType = "system"
	SessionDetailSessionTypeTopicGuided      SessionDetailSessionType = "topic_guided"
	SessionDetailSessionTypeUserAdded        SessionDetailSessionType = "user_added"
)

// Valid indicates whether the value is a known member of the SessionDetailSessionType enum.
func (e SessionDetailSessionType) Valid() bool {
	switch e {
	case SessionDetailSessionTypeExpressionGuided:
		return true
	case SessionDetailSessionTypeSystem:
		return true
	case SessionDetailSessionTypeTopicGuided:
		return true
	case SessionDetailSessionTypeUserAdded:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailStatus.
const (
	SessionDetailStatusComplete   SessionDetailStatus = "complete"
	SessionDetailStatusFailed     SessionDetailStatus = "failed"
	SessionDetailStatusGenerating SessionDetailStatus = "generating"
	SessionDetailStatusPending    SessionDetailStatus = "pending"
	SessionDetailStatusReading    SessionDetailStatus = "reading"
	SessionDetailStatusReady      SessionDetailStatus = "ready"
)

// Valid indicates whether the value is a known member of the SessionDetailStatus enum.
func (e SessionDetailStatus) Valid() bool {
	switch e {
	case SessionDetailStatusComplete:
		return true
	case SessionDetailStatusFailed:
		return true
	case SessionDetailStatusGenerating:
		return true
	case SessionDetailStatusPending:
		return true
	case SessionDetailStatusReading:
		return true
	case SessionDetailStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewContentType.
const (
	SessionOverviewContentTypePhraseSet SessionOverviewContentType = "phrase_set"
	SessionOverviewContentTypeStory     SessionOverviewContentType = "story"
)

// Valid indicates whether the value is a known member of the SessionOverviewContentType enum.
func (e SessionOverviewContentType) Valid() bool {
	switch e {
	case SessionOverviewContentTypePhraseSet:
		return true
	case SessionOverviewContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewExpressionOutput.
const (
	Phrases SessionOverviewExpressionOutput = "phrases"
	Story   SessionOverviewExpressionOutput = "story"
)

// Valid indicates whether the value is a known member of the SessionOverviewExpressionOutput enum.
func (e SessionOverviewExpressionOutput) Valid() bool {
	switch e {
	case Phrases:
		return true
	case Story:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewSessionType.
const (
	ExpressionGuided SessionOverviewSessionType = "expression_guided"
	System           SessionOverviewSessionType = "system"
	TopicGuided      SessionOverviewSessionType = "topic_guided"
	UserAdded        SessionOverviewSessionType = "user_added"
)

// Valid indicates whether the value is a known member of the SessionOverviewSessionType enum.
func (e SessionOverviewSessionType) Valid() bool {
	switch e {
	case ExpressionGuided:
		return true
	case System:
		return true
	case TopicGuided:
		return true
	case UserAdded:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewStatus.
const (
	SessionOverviewStatusComplete   SessionOverviewStatus = "complete"
	SessionOverviewStatusFailed     SessionOverviewStatus = "failed"
	SessionOverviewStatusGenerating SessionOverviewStatus = "generating"
	SessionOverviewStatusPending    SessionOverviewStatus = "pending"
	SessionOverviewStatusReading    SessionOverviewStatus = "reading"
	SessionOverviewStatusReady      SessionOverviewStatus = "ready"
)

// Valid indicates whether the value is a known member of the SessionOverviewStatus enum.
func (e SessionOverviewStatus) Valid() bool {
	switch e {
	case SessionOverviewStatusComplete:
		return true
	case SessionOverviewStatusFailed:
		return true
	case SessionOverviewStatusGenerating:
		return true
	case SessionOverviewStatusPending:
		return true
	case SessionOverviewStatusReading:
		return true
	case SessionOverviewStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for StartConversationRequestLevel.
const (
	StartConversationLevelAdvanced          StartConversationRequestLevel = "advanced"
	StartConversationLevelBeginner          StartConversationRequestLevel = "beginner"
	StartConversationLevelElementary        StartConversationRequestLevel = "elementary"
	StartConversationLevelIntermediate      StartConversationRequestLevel = "intermediate"
	StartConversationLevelUpperIntermediate StartConversationRequestLevel = "upper-intermediate"
)

// Valid indicates whether the value is a known member of the StartConversationRequestLevel enum.
func (e StartConversationRequestLevel) Valid() bool {
	switch e {
	case StartConversationLevelAdvanced:
		return true
	case StartConversationLevelBeginner:
		return true
	case StartConversationLevelElementary:
		return true
	case StartConversationLevelIntermediate:
		return true
	case StartConversationLevelUpperIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for SubmitTaskRequestInputMethod.
const (
	Typed SubmitTaskRequestInputMethod = "typed"
)

// Valid indicates whether the value is a known member of the SubmitTaskRequestInputMethod enum.
func (e SubmitTaskRequestInputMethod) Valid() bool {
	switch e {
	case Typed:
		return true
	default:
		return false
	}
}

// Defines values for TargetPreviewGuessKind.
const (
	NoIdea TargetPreviewGuessKind = "no_idea"
	Text   TargetPreviewGuessKind = "text"
)

// Valid indicates whether the value is a known member of the TargetPreviewGuessKind enum.
func (e TargetPreviewGuessKind) Valid() bool {
	switch e {
	case NoIdea:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for TaskReportReason.
const (
	Malformed      TaskReportReason = "malformed"
	Nonsensical    TaskReportReason = "nonsensical"
	TooHard        TaskReportReason = "too_hard"
	WrongAnswerKey TaskReportReason = "wrong_answer_key"
)

// Valid indicates whether the value is a known member of the TaskReportReason enum.
func (e TaskReportReason) Valid() bool {
	switch e {
	case Malformed:
		return true
	case Nonsensical:
		return true
	case TooHard:
		return true
	case WrongAnswerKey:
		return true
	default:
		return false
	}
}

// Defines values for TaskReportStatus.
const (
	Answered     TaskReportStatus = "answered"
	CapReached   TaskReportStatus = "cap_reached"
	Failed       TaskReportStatus = "failed"
	None         TaskReportStatus = "none"
	Queued       TaskReportStatus = "queued"
	Regenerated  TaskReportStatus = "regenerated"
	Regenerating TaskReportStatus = "regenerating"
	Unavailable  TaskReportStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the TaskReportStatus enum.
func (e TaskReportStatus) Valid() bool {
	switch e {
	case Answered:
		return true
	case CapReached:
		return true
	case Failed:
		return true
	case None:
		return true
	case Queued:
		return true
	case Regenerated:
		return true
	case Regenerating:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for WordKnowledgeRequestLevel.
const (
	WordKnowledgeRequestLevelEmpty     WordKnowledgeRequestLevel = ""
	WordKnowledgeRequestLevelIgnored   WordKnowledgeRequestLevel = "ignored"
	WordKnowledgeRequestLevelN1        WordKnowledgeRequestLevel = "1"
	WordKnowledgeRequestLevelN2        WordKnowledgeRequestLevel = "2"
	WordKnowledgeRequestLevelN3        WordKnowledgeRequestLevel = "3"
	WordKnowledgeRequestLevelN4        WordKnowledgeRequestLevel = "4"
	WordKnowledgeRequestLevelN5        WordKnowledgeRequestLevel = "5"
	WordKnowledgeRequestLevelWellKnown WordKnowledgeRequestLevel = "well_known"
)

// Valid indicates whether the value is a known member of the WordKnowledgeRequestLevel enum.
func (e WordKnowledgeRequestLevel) Valid() bool {
	switch e {
	case WordKnowledgeRequestLevelEmpty:
		return true
	case WordKnowledgeRequestLevelIgnored:
		return true
	case WordKnowledgeRequestLevelN1:
		return true
	case WordKnowledgeRequestLevelN2:
		return true
	case WordKnowledgeRequestLevelN3:
		return true
	case WordKnowledgeRequestLevelN4:
		return true
	case WordKnowledgeRequestLevelN5:
		return true
	case WordKnowledgeRequestLevelWellKnown:
		return true
	default:
		return false
	}
}

// Defines values for AdminListCallsParamsStatus.
const (
	Error   AdminListCallsParamsStatus = "error"
	Success AdminListCallsParamsStatus = "success"
	Timeout AdminListCallsParamsStatus = "timeout"
)

// Valid indicates whether the value is a known member of the AdminListCallsParamsStatus enum.
func (e AdminListCallsParamsStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Success:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// Defines values for GetConversationTurnAudioParamsPart.
const (
	Feedback GetConversationTurnAudioParamsPart = "feedback"
	Passage  GetConversationTurnAudioParamsPart = "passage"
	Prompt   GetConversationTurnAudioParamsPart = "prompt"
)

// Valid indicates whether the value is a known member of the GetConversationTurnAudioParamsPart enum.
func (e GetConversationTurnAudioParamsPart) Valid() bool {
	switch e {
	case Feedback:
		return true
	case Passage:
		return true
	case Prompt:
		return true
	default:
		return false
	}
}

// AdminCallLog A page of the global call log, filtered and paginated.
type AdminCallLog struct {
	Calls   []LLMCallLogRow `json:"calls"`
	HasMore bool            `json:"has_more"`
	Limit   int             `json:"limit"`
	Offset  int             `json:"offset"`
}

// AdminContext The current caller's admin capability. Only admins reach this endpoint (non-admins get 404 like every /admin route), so is_admin is always true in a 200 response; the client treats a 404 as "not an admin" (#24).
type AdminContext struct {
	IsAdmin bool `json:"is_admin"`
}

// AdminCostRollup Global spend for a time window, grouped by day × model.
type AdminCostRollup struct {
	Buckets []CostBucket `json:"buckets"`

	// Total Aggregate cost of a set of calls, deriving unknown pricing honestly.
	Total      CostSummary `json:"total"`
	WindowFrom float64     `json:"window_from,omitempty"`
	WindowTo   float64     `json:"window_to,omitempty"`
}

// AdminUserDetail Admin lookup of one user — their sessions plus cost rollups.
type AdminUserDetail struct {
	CostByDay   []CostBucket      `json:"cost_by_day"`
	CostByModel []CostBucket      `json:"cost_by_model"`
	Sessions    []SessionOverview `json:"sessions"`
	User        User              `json:"user"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
	User        User   `json:"user"`
}

// BreakdownTrace Debug-safe source trace for a reader breakdown lookup.
type BreakdownTrace struct {
	CacheHit  bool                    `json:"cache_hit"`
	CacheKey  string                  `json:"cache_key"`
	CreatedAt float64                 `json:"created_at,omitempty"`
	Language  string                  `json:"language"`
	Scope     BreakdownTraceScope     `json:"scope"`
	Sentence  *SentenceBreakdownTrace `json:"sentence,omitempty"`
	Source    BreakdownTraceSource    `json:"source"`
	Word      *WordBreakdownTrace     `json:"word,omitempty"`
}

// BreakdownTraceScope defines model for BreakdownTrace.Scope.
type BreakdownTraceScope string

// BreakdownTraceSource defines model for BreakdownTrace.Source.
type BreakdownTraceSource string

// Conversation defines model for Conversation.
type Conversation struct {
	ConversationId string             `json:"conversation_id"`
	CreatedAt      float64            `json:"created_at"`
	Language       string             `json:"language"`
	Level          string             `json:"level"`
	RepairDepth    int                `json:"repair_depth"`
	SourceText     string             `json:"source_text"`
	Status         ConversationStatus `json:"status"`

	// StorySummary Compact main-narrative memory; repair stories do not replace it.
	StorySummary string             `json:"story_summary"`
	Topic        string             `json:"topic"`
	Turns        []ConversationTurn `json:"turns"`
	UpdatedAt    float64            `json:"updated_at"`
}

// ConversationStatus defines model for Conversation.Status.
type ConversationStatus string

// ConversationAudioResponseRequest defines model for ConversationAudioResponseRequest.
type ConversationAudioResponseRequest struct {
	// File Browser-recorded audio in a format supported by the configured audio-server.
	File openapi_types.File `json:"file"`
}

// ConversationList defines model for ConversationList.
type ConversationList struct {
	Conversations []ConversationSummary `json:"conversations"`
}

// ConversationSummary defines model for ConversationSummary.
type ConversationSummary struct {
	ConversationId string  `json:"conversation_id"`
	CreatedAt      float64 `json:"created_at"`
	Language       string  `json:"language"`
	Level          string  `json:"level"`
	RepairDepth    int     `json:"repair_depth"`
	Status         string  `json:"status"`
	StorySummary   string  `json:"story_summary"`
	Topic          string  `json:"topic"`
	TurnCount      int     `json:"turn_count"`
	UpdatedAt      float64 `json:"updated_at"`
}

// ConversationTranscription defines model for ConversationTranscription.
type ConversationTranscription struct {
	Text string `json:"text"`
}

// ConversationTurn defines model for ConversationTurn.
type ConversationTurn struct {
	Action     ConversationTurnAction     `json:"action,omitempty"`
	Assessment ConversationTurnAssessment `json:"assessment,omitempty"`

	// AudioUrl API-root-relative authenticated path that generates assistant TTS audio.
	AudioUrl  string  `json:"audio_url,omitempty"`
	CreatedAt float64 `json:"created_at"`

	// EnglishText Brief correction or teaching feedback.
	EnglishText string `json:"english_text,omitempty"`

	// Focus The specific word or construction targeted by a repair story.
	Focus string `json:"focus,omitempty"`

	// GreekText Target-language passage; suitable for display and future TTS.
	GreekText string `json:"greek_text,omitempty"`

	// InputText Typed learner response.
	InputText string               `json:"input_text,omitempty"`
	Kind      ConversationTurnKind `json:"kind"`

	// PromptText Learner-facing request for a translation/uncertainty report.
	PromptText    string               `json:"prompt_text,omitempty"`
	ReplyToTurnId string               `json:"reply_to_turn_id,omitempty"`
	Role          ConversationTurnRole `json:"role"`

	// Transcript STT output for spoken learner input.
	Transcript string `json:"transcript,omitempty"`
	TurnId     string `json:"turn_id"`
}

// ConversationTurnAction defines model for ConversationTurn.Action.
type ConversationTurnAction string

// ConversationTurnAssessment defines model for ConversationTurn.Assessment.
type ConversationTurnAssessment string

// ConversationTurnKind defines model for ConversationTurn.Kind.
type ConversationTurnKind string

// ConversationTurnRole defines model for ConversationTurn.Role.
type ConversationTurnRole string

// CostBucket One aggregation bucket of LLM spend. day and/or model are set depending on how the rollup was grouped. cost_usd is present only when every call in the bucket had known pricing (cost_known true); a bucket for an unpriced model reports cost_known false rather than a misleading zero.
type CostBucket struct {
	Calls     int     `json:"calls"`
	CostKnown bool    `json:"cost_known"`
	CostUsd   float64 `json:"cost_usd,omitempty"`

	// Day UTC calendar day (YYYY-MM-DD); present for day-grouped buckets.
	Day         string `json:"day,omitempty"`
	InputTokens int64  `json:"input_tokens"`

	// Model Model name; present for model-grouped buckets.
	Model        string `json:"model,omitempty"`
	OutputTokens int64  `json:"output_tokens"`
}

// CostSummary Aggregate cost of a set of calls, deriving unknown pricing honestly.
type CostSummary struct {
	// HasUnknown True when at least one call's model lacked pricing, so total_usd understates spend.
	HasUnknown bool `json:"has_unknown"`

	// TotalUsd Sum of costs over calls whose model had configured pricing.
	TotalUsd float64 `json:"total_usd"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Definition A resolved word definition for the reader popup.
type Definition struct {
	Etymology       string `json:"etymology,omitempty"`
	Example         string `json:"example,omitempty"`
	Gloss           string `json:"gloss"`
	GrammaticalNote string `json:"grammatical_note,omitempty"`
	Key             string `json:"key"`
	Notes           string `json:"notes,omitempty"`

	// Source where the definition came from
	Source DefinitionSource `json:"source"`

	// Trace Debug-safe source trace for a reader definition lookup.
	Trace DefinitionTrace `json:"trace"`
}

// DefinitionSource where the definition came from
type DefinitionSource string

// DefinitionOption One stored definition that can be selected in the reader source picker.
type DefinitionOption struct {
	Etymology       string                 `json:"etymology,omitempty"`
	Example         string                 `json:"example,omitempty"`
	Gloss           string                 `json:"gloss"`
	GrammaticalNote string                 `json:"grammatical_note,omitempty"`
	Key             string                 `json:"key"`
	Notes           string                 `json:"notes,omitempty"`
	Source          DefinitionOptionSource `json:"source"`
}

// DefinitionOptionSource defines model for DefinitionOption.Source.
type DefinitionOptionSource string

// DefinitionTrace Debug-safe source trace for a reader definition lookup.
type DefinitionTrace struct {
	QueryKey      string                       `json:"query_key"`
	ResolvedKey   string                       `json:"resolved_key"`
	Steps         []DefinitionTraceStep        `json:"steps"`
	WinningSource DefinitionTraceWinningSource `json:"winning_source"`
}

// DefinitionTraceWinningSource defines model for DefinitionTrace.WinningSource.
type DefinitionTraceWinningSource string

// DefinitionTraceStep One checked source in the ordered definition lookup chain.
type DefinitionTraceStep struct {
	Count     int                       `json:"count,omitempty"`
	Key       string                    `json:"key,omitempty"`
	Reason    string                    `json:"reason,omitempty"`
	Source    DefinitionTraceStepSource `json:"source,omitempty"`
	Status    DefinitionTraceStepStatus `json:"status"`
	Step      DefinitionTraceStepStep   `json:"step"`
	TargetKey string                    `json:"target_key,omitempty"`
}

// DefinitionTraceStepSource defines model for DefinitionTraceStep.Source.
type DefinitionTraceStepSource string

// DefinitionTraceStepStatus defines model for DefinitionTraceStep.Status.
type DefinitionTraceStepStatus string

// DefinitionTraceStepStep defines model for DefinitionTraceStep.Step.
type DefinitionTraceStepStep string

// DictionaryEntry A caller-owned dictionary override for one canonical word key.
type DictionaryEntry struct {
	Gloss    string `json:"gloss"`
	Key      string `json:"key"`
	Language string `json:"language"`
	Notes    string `json:"notes,omitempty"`
}

// DictionaryEntryRequest defines model for DictionaryEntryRequest.
type DictionaryEntryRequest struct {
	Gloss string `json:"gloss"`

	// Key canonical knowledge key
	Key      string `json:"key"`
	Language string `json:"language"`
	Notes    string `json:"notes,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// ExpressionOutput expression_guided only
	ExpressionOutput GenerateRequestExpressionOutput `json:"expression_output,omitempty"`

	// Language registered enabled language code, e.g. 'el'; defaults to profile.active_language
	Language string `json:"language,omitempty"`

	// Level beginner|elementary|intermediate|upper-intermediate|advanced; defaults to derived verified skill level when available, otherwise profile.level
	Level       string                     `json:"level,omitempty"`
	SessionType GenerateRequestSessionType `json:"session_type,omitempty"`

	// Topic topic_guided only
	Topic string `json:"topic,omitempty"`

	// UserExpressions expression_guided only
	UserExpressions []string `json:"user_expressions,omitempty"`
}

// GenerateRequestExpressionOutput expression_guided only
type GenerateRequestExpressionOutput string

// GenerateRequestSessionType defines model for GenerateRequest.SessionType.
type GenerateRequestSessionType string

// GenerationEvent One SSE progress message (the JSON in each data line). Non-terminal events report a pipeline stage status. The terminal `stage: done` event reports the final session status plus enough persisted state for the client to navigate to reader/tasks or show retry/error UI without guessing.
type GenerationEvent struct {
	// ContentType present on stage=done; whether the session produced a story (load via /stories/{id}) or a phrase set (load via /sessions/{id}/content)
	ContentType GenerationEventContentType `json:"content_type,omitempty"`

	// ErrorCode stable code on failed progress events and failed terminal events; GEN_SCOPE_REJECTED means a topic-guided topic was out of scope for the learner level
	ErrorCode string `json:"error_code,omitempty"`

	// ErrorDetail human-readable failure reason on failed terminal events, e.g. why a topic was rejected and an optional simpler rephrasing to try
	ErrorDetail string `json:"error_detail,omitempty"`

	// FailedStage first failed stage, present on failed terminal events
	FailedStage string `json:"failed_stage,omitempty"`

	// SessionId present on stage=done
	SessionId string `json:"session_id,omitempty"`

	// Stage scope_check|selection|story_import|story_generation|phrase_generation|tokenization|task_<type>|done
	Stage        string        `json:"stage"`
	StageSummary *StageSummary `json:"stage_summary,omitempty"`

	// Status stage status for progress events; final session status for stage=done
	Status GenerationEventStatus `json:"status,omitempty"`

	// StoryId present on stage=done once a story has been persisted
	StoryId string `json:"story_id,omitempty"`

	// SuggestedTopic on GEN_SCOPE_REJECTED events, a simpler in-scope rephrasing of the rejected topic the client can offer as a retry
	SuggestedTopic string        `json:"suggested_topic,omitempty"`
	Tasks          *TaskProgress `json:"tasks,omitempty"`

	// TokenRate approx upstream tokens/sec
	TokenRate int `json:"token_rate,omitempty"`
}

// GenerationEventContentType present on stage=done; whether the session produced a story (load via /stories/{id}) or a phrase set (load via /sessions/{id}/content)
type GenerationEventContentType string

// GenerationEventStatus stage status for progress events; final session status for stage=done
type GenerationEventStatus string

// GenerationStageRecord defines model for GenerationStageRecord.
type GenerationStageRecord struct {
	CompletedAt float64                     `json:"completed_at,omitempty"`
	ErrorCode   string                      `json:"error_code,omitempty"`
	ErrorDetail string                      `json:"error_detail,omitempty"`
	RetryCount  int                         `json:"retry_count"`
	Stage       string                      `json:"stage"`
	StartedAt   float64                     `json:"started_at,omitempty"`
	Status      GenerationStageRecordStatus `json:"status"`
}

// GenerationStageRecordStatus defines model for GenerationStageRecord.Status.
type GenerationStageRecordStatus string

// Grade The outcome of grading one task response.
type Grade struct {
	Correct  bool          `json:"correct"`
	Feedback string        `json:"feedback,omitempty"`
	GradedBy GradeGradedBy `json:"graded_by"`

	// ItemsDemonstrated knowledge item ids the response demonstrated
	ItemsDemonstrated []string `json:"items_demonstrated,omitempty"`

	// Score 0.0..1.0
	Score float64 `json:"score"`
}

// GradeGradedBy defines model for Grade.GradedBy.
type GradeGradedBy string

// ImportStoryRequest defines model for ImportStoryRequest.
type ImportStoryRequest struct {
	// Language registered enabled language code, e.g. 'el'; defaults to profile.active_language
	Language string `json:"language,omitempty"`

	// Level beginner|elementary|intermediate|upper-intermediate|advanced; defaults to profile.level
	Level string `json:"level,omitempty"`

	// Text raw target-language text to tokenize for the reader
	Text string `json:"text"`

	// Title optional user-facing label stored as imported-story metadata
	Title string `json:"title,omitempty"`
}

// ImportStoryResponse defines model for ImportStoryResponse.
type ImportStoryResponse struct {
	Language  string `json:"language"`
	SessionId string `json:"session_id"`
	StoryId   string `json:"story_id"`
	Title     string `json:"title,omitempty"`
}

// ImportStoryUploadRequest defines model for ImportStoryUploadRequest.
type ImportStoryUploadRequest struct {
	// File UTF-8 text/plain .txt file, at most 512 KiB
	File openapi_types.File `json:"file"`

	// Language registered enabled language code, e.g. 'el'; defaults to profile.active_language
	Language string `json:"language,omitempty"`

	// Level beginner|elementary|intermediate|upper-intermediate|advanced; defaults to profile.level
	Level string `json:"level,omitempty"`

	// Title optional user-facing label stored as imported-story metadata
	Title string `json:"title,omitempty"`
}

// ImportedStory One row in the imported-story (standalone reader content) list.
type ImportedStory struct {
	CreatedAt float64 `json:"created_at"`
	Language  string  `json:"language"`
	Level     string  `json:"level"`
	StoryId   string  `json:"story_id"`

	// Title clean display title — the "Imported: " topic prefix is stripped and untitled imports fall back to the first words of the text.
	Title string `json:"title"`
}

// ImportedStoryList defines model for ImportedStoryList.
type ImportedStoryList struct {
	HasMore bool            `json:"has_more"`
	Limit   int             `json:"limit"`
	Offset  int             `json:"offset"`
	Stories []ImportedStory `json:"stories"`
}

// LLMCall One llm_calls audit row scoped to a session and current user.
type LLMCall struct {
	CallId   string  `json:"call_id"`
	CalledAt float64 `json:"called_at"`

	// CostKnown Whether this call's model has configured pricing. When false the cost is unknown (not zero) and clients render it as such (#24).
	CostKnown bool `json:"cost_known"`

	// CostUsd Derived USD cost (input+output tokens × configured model pricing). Present only when cost_known is true.
	CostUsd     float64 `json:"cost_usd,omitempty"`
	ErrorDetail string  `json:"error_detail,omitempty"`

	// ErrorPayload Raw gateway error response body when available.
	ErrorPayload string `json:"error_payload,omitempty"`
	InputTokens  int    `json:"input_tokens,omitempty"`
	Kind         string `json:"kind"`
	LatencyMs    int    `json:"latency_ms,omitempty"`
	Model        string `json:"model"`
	OutputTokens int    `json:"output_tokens,omitempty"`

	// ParsedOutput Assistant content extracted from the provider envelope when available. If no separate parsed payload exists for a call, clients should use raw_response for debugging.
	ParsedOutput  string `json:"parsed_output,omitempty"`
	PromptVersion string `json:"prompt_version"`

	// RawResponse Raw gateway response body. On successful calls this is the provider envelope.
	RawResponse string        `json:"raw_response,omitempty"`
	SessionId   string        `json:"session_id,omitempty"`
	Status      LLMCallStatus `json:"status"`

	// SystemPrompt System prompt sent to the LLM gateway when present.
	SystemPrompt string `json:"system_prompt,omitempty"`
	UserId       string `json:"user_id,omitempty"`

	// UserPrompt User prompt sent to the LLM gateway.
	UserPrompt string `json:"user_prompt,omitempty"`
}

// LLMCallStatus defines model for LLMCall.Status.
type LLMCallStatus string

// LLMCallLogRow One row of the admin global call log (#24/#134). Deliberately omits the prompt/response payload columns so the list stays cheap and logs do not leak into casual scrolling; fetch full payloads per call via GET /admin/calls/{id}.
type LLMCallLogRow struct {
	CallId        string              `json:"call_id"`
	CalledAt      float64             `json:"called_at"`
	CostKnown     bool                `json:"cost_known"`
	CostUsd       float64             `json:"cost_usd,omitempty"`
	ErrorDetail   string              `json:"error_detail,omitempty"`
	InputTokens   int                 `json:"input_tokens,omitempty"`
	Kind          string              `json:"kind"`
	LatencyMs     int                 `json:"latency_ms,omitempty"`
	Model         string              `json:"model"`
	OutputTokens  int                 `json:"output_tokens,omitempty"`
	PromptVersion string              `json:"prompt_version"`
	SessionId     string              `json:"session_id,omitempty"`
	Status        LLMCallLogRowStatus `json:"status"`
	UserId        string              `json:"user_id,omitempty"`
}

// LLMCallLogRowStatus defines model for LLMCallLogRow.Status.
type LLMCallLogRowStatus string

// LLMModel defines model for LLMModel.
type LLMModel struct {
	// ContextLength Maximum context length when provided by the upstream.
	ContextLength int `json:"context_length,omitempty"`

	// Description Upstream model description.
	Description string `json:"description,omitempty"`

	// Id Provider model id.
	Id string `json:"id"`

	// Name Display name when provided by the upstream.
	Name string `json:"name,omitempty"`
}

// Language defines model for Language.
type Language struct {
	Code        string              `json:"code"`
	Enabled     bool                `json:"enabled"`
	KeyStrategy LanguageKeyStrategy `json:"key_strategy"`
	Name        string              `json:"name"`
}

// LanguageKeyStrategy defines model for Language.KeyStrategy.
type LanguageKeyStrategy string

// MediaURL Server-issued access URL for task media. Clients should treat the URL as a refreshable bearer grant, not as durable storage identity.
type MediaURL struct {
	ContentType string `json:"content_type"`

	// ExpiresAt Unix seconds when the client should refresh the URL.
	ExpiresAt int64 `json:"expires_at"`
	Size      int64 `json:"size"`

	// Url Browser-safe URL for this task's media object.
	Url string `json:"url"`
}

// PhraseAnnotation defines model for PhraseAnnotation.
type PhraseAnnotation struct {
	// Kind e.g. construction | vocabulary
	Kind  string `json:"kind"`
	Label string `json:"label,omitempty"`
	Note  string `json:"note,omitempty"`
}

// PhraseItem One phrase plus the annotations that explain what it teaches.
type PhraseItem struct {
	Annotations []PhraseAnnotation `json:"annotations,omitempty"`

	// Gloss English translation
	Gloss    string `json:"gloss,omitempty"`
	Notes    string `json:"notes,omitempty"`
	PhraseId string `json:"phrase_id"`

	// TargetItemIds knowledge item ids this phrase practises
	TargetItemIds []string `json:"target_item_ids,omitempty"`

	// TargetText the target-language phrase
	TargetText string `json:"target_text"`
}

// PhraseSet The content of an expression-guided phrase session.
type PhraseSet struct {
	Items     []PhraseItem `json:"items"`
	Language  string       `json:"language"`
	SessionId string       `json:"session_id"`
}

// Profile defines model for Profile.
type Profile struct {
	// ActiveLanguage enabled language code used when generation omits language
	ActiveLanguage string `json:"active_language"`

	// Level stored level fallback; session generation may derive a fresher value from verified skill tiers
	Level ProfileLevel `json:"level"`

	// LlmModel model id requested for LLM calls; blank uses the gateway default
	LlmModel string `json:"llm_model"`

	// Preferences arbitrary client-owned preferences; product-critical fields remain top-level
	Preferences map[string]interface{} `json:"preferences"`

	// Theme theme id, e.g. 'default' or 'high-contrast'
	Theme string `json:"theme"`

	// TtsModel audio-server TTS model; blank uses the server default
	TtsModel string `json:"tts_model"`

	// UiLanguage BCP-47 style UI/gloss language tag, e.g. 'en'
	UiLanguage string `json:"ui_language"`
	UserId     string `json:"user_id"`
}

// ProfileLevel stored level fallback; session generation may derive a fresher value from verified skill tiers
type ProfileLevel string

// ProfilePatch defines model for ProfilePatch.
type ProfilePatch struct {
	// ActiveLanguage must name an enabled language
	ActiveLanguage string `json:"active_language,omitempty"`

	// Level stored level fallback; clients should not treat this as arbitrary preference state
	Level ProfilePatchLevel `json:"level,omitempty"`

	// LlmModel OpenAI/OpenRouter-compatible model id; empty string clears to the gateway default
	LlmModel string `json:"llm_model,omitempty"`

	// Preferences shallow-merged; null values delete keys
	Preferences map[string]interface{} `json:"preferences,omitempty"`

	// Theme letters, numbers, '_' and '-' only
	Theme string `json:"theme,omitempty"`

	// TtsModel audio-server TTS model id; empty string clears to the server default
	TtsModel string `json:"tts_model,omitempty"`

	// UiLanguage BCP-47 style UI/gloss language tag
	UiLanguage string `json:"ui_language,omitempty"`
}

// ProfilePatchLevel stored level fallback; clients should not treat this as arbitrary preference state
type ProfilePatchLevel string

// ReaderEvent One logged reader interaction.
type ReaderEvent struct {
	// EventId client idempotency key; generated if omitted
	EventId   string               `json:"event_id,omitempty"`
	EventType ReaderEventEventType `json:"event_type"`

	// OccurredAt Unix seconds (client clock)
	OccurredAt float64 `json:"occurred_at,omitempty"`

	// Position story token position the event is about
	Position  *int   `json:"position,omitempty"`
	SessionId string `json:"session_id,omitempty"`
	StoryId   string `json:"story_id"`

	// TaskIds reference_peek only: unanswered tasks the peek applies to
	TaskIds []string `json:"task_ids,omitempty"`

	// Value rate only: "1".."5" | "w" | "i"; server may store event-specific metadata here
	Value string `json:"value,omitempty"`
}

// ReaderEventEventType defines model for ReaderEvent.EventType.
type ReaderEventEventType string

// ReaderEventsRequest defines model for ReaderEventsRequest.
type ReaderEventsRequest struct {
	Events []ReaderEvent `json:"events"`
}

// ReaderKnowledge The reader's canonical per-item view, keyed by lemma/root/stem key.
type ReaderKnowledge struct {
	// Level explicit canonical learner mark; '' (omitted)=none
	Level       ReaderKnowledgeLevel `json:"level"`
	LookupCount int                  `json:"lookup_count"`
}

// ReaderKnowledgeLevel explicit canonical learner mark; ” (omitted)=none
type ReaderKnowledgeLevel string

// ReaderSentenceAlignment Forced alignment between one synthesized sentence and its story word tokens.
type ReaderSentenceAlignment struct {
	SentenceIndex int                `json:"sentence_index"`
	Words         []ReaderWordTiming `json:"words"`
}

// ReaderSurfaceKnowledge The reader's per-displayed-form level, keyed by StoryToken.form_key.
type ReaderSurfaceKnowledge struct {
	// Level learner self-rating for this exact form; ''=unseen
	Level ReaderSurfaceKnowledgeLevel `json:"level"`
}

// ReaderSurfaceKnowledgeLevel learner self-rating for this exact form; ”=unseen
type ReaderSurfaceKnowledgeLevel string

// ReaderSurfaceKnowledgeRequest defines model for ReaderSurfaceKnowledgeRequest.
type ReaderSurfaceKnowledgeRequest struct {
	// ItemKey canonical lemma/root/stem key for the token
	ItemKey  string `json:"item_key"`
	Language string `json:"language"`

	// Level '' clears to unseen for this exact form
	Level ReaderSurfaceKnowledgeRequestLevel `json:"level"`

	// SurfaceKey StoryToken.surface_key for the displayed form
	SurfaceKey string `json:"surface_key"`
}

// ReaderSurfaceKnowledgeRequestLevel ” clears to unseen for this exact form
type ReaderSurfaceKnowledgeRequestLevel string

// ReaderTrace One reader-side trace row included in the session debug payload. Rows are derived from stored data only; debug reads do not trigger new lookup, breakdown, Wiktionary, or LLM work.
type ReaderTrace struct {
	BreakdownTrace *BreakdownTrace `json:"breakdown_trace,omitempty"`

	// CreatedAt Unix seconds for cached breakdown rows, when available.
	CreatedAt       float64          `json:"created_at,omitempty"`
	DefinitionTrace *DefinitionTrace `json:"definition_trace,omitempty"`

	// Key Word/item key for definition and word-breakdown rows.
	Key      string          `json:"key,omitempty"`
	Kind     ReaderTraceKind `json:"kind"`
	Language string          `json:"language"`

	// Position Token position for the row's story context.
	Position int `json:"position"`

	// Source Winning definition source, or breakdown source such as cache/llm.
	Source  string            `json:"source"`
	Status  ReaderTraceStatus `json:"status"`
	StoryId string            `json:"story_id"`
}

// ReaderTraceKind defines model for ReaderTrace.Kind.
type ReaderTraceKind string

// ReaderTraceStatus defines model for ReaderTrace.Status.
type ReaderTraceStatus string

// ReaderWordTiming defines model for ReaderWordTiming.
type ReaderWordTiming struct {
	End      float64 `json:"end"`
	Position int     `json:"position"`
	Start    float64 `json:"start"`
	Surface  string  `json:"surface"`
}

// RespondConversationRequest defines model for RespondConversationRequest.
type RespondConversationRequest struct {
	// Text The learner's best English translation and any unclear parts.
	Text string `json:"text"`
}

// SelectedItemCounts Persisted SelectedItems counts; background items are not currently stored.
type SelectedItemCounts struct {
	New     int `json:"new"`
	Targets int `json:"targets"`
}

// SentenceBreakdownTrace Sentence-specific breakdown trace metadata.
type SentenceBreakdownTrace struct {
	PhraseCacheMatchCount int `json:"phrase_cache_match_count"`

	// Span Authoritative sentence boundary over story token positions. Positions are half-open: tokens with position >= start_position and < end_position are part of the sentence. Text is exactly the sentence text used by the sentence-breakdown cache key.
	Span              SentenceSpan                        `json:"span"`
	StructureHint     SentenceBreakdownTraceStructureHint `json:"structure_hint"`
	StructureKey      string                              `json:"structure_key,omitempty"`
	StructureTemplate string                              `json:"structure_template,omitempty"`
}

// SentenceBreakdownTraceStructureHint defines model for SentenceBreakdownTrace.StructureHint.
type SentenceBreakdownTraceStructureHint string

// SentenceSpan Authoritative sentence boundary over story token positions. Positions are half-open: tokens with position >= start_position and < end_position are part of the sentence. Text is exactly the sentence text used by the sentence-breakdown cache key.
type SentenceSpan struct {
	// EndPosition One past the final token position in the sentence.
	EndPosition int `json:"end_position"`

	// Index 0-indexed sentence number within the story.
	Index int `json:"index"`

	// StartPosition First token position in the sentence, inclusive.
	StartPosition int `json:"start_position"`

	// Text Readable sentence text reconstructed from story tokens.
	Text string `json:"text"`
}

// SessionContent A session's content, discriminated by content_type. Exactly one of story or phrase_set is present.
type SessionContent struct {
	ContentType SessionContentContentType `json:"content_type"`
	PhraseSet   *PhraseSet                `json:"phrase_set,omitempty"`
	SessionId   string                    `json:"session_id"`
	Story       *StoryContentRef          `json:"story,omitempty"`
}

// SessionContentContentType defines model for SessionContent.ContentType.
type SessionContentContentType string

// SessionDebug defines model for SessionDebug.
type SessionDebug struct {
	// Cost Aggregate cost of a set of calls, deriving unknown pricing honestly.
	Cost         CostSummary   `json:"cost"`
	LlmCalls     []LLMCall     `json:"llm_calls"`
	ReaderTraces []ReaderTrace `json:"reader_traces"`
	Session      SessionDetail `json:"session"`
}

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	ArchivedAt  float64 `json:"archived_at,omitempty"`
	CompletedAt float64 `json:"completed_at,omitempty"`

	// ContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
	ContentType      SessionDetailContentType      `json:"content_type"`
	CreatedAt        float64                       `json:"created_at"`
	ExpressionOutput SessionDetailExpressionOutput `json:"expression_output,omitempty"`
	Language         string                        `json:"language"`
	Level            string                        `json:"level"`
	ReadingStartedAt float64                       `json:"reading_started_at,omitempty"`

	// SelectedCounts Persisted SelectedItems counts; background items are not currently stored.
	SelectedCounts SelectedItemCounts       `json:"selected_counts"`
	SessionId      string                   `json:"session_id"`
	SessionType    SessionDetailSessionType `json:"session_type"`
	StageSummary   StageSummary             `json:"stage_summary"`
	Stages         []GenerationStageRecord  `json:"stages"`
	Status         SessionDetailStatus      `json:"status"`

	// StoryId present once a story has been persisted for the session
	StoryId string `json:"story_id,omitempty"`

	// TargetPreview Selected targets and any ungraded preview attempts for this session.
	TargetPreview   TargetPreview `json:"target_preview,omitempty"`
	Tasks           TaskProgress  `json:"tasks"`
	Topic           string        `json:"topic,omitempty"`
	UserExpressions []string      `json:"user_expressions,omitempty"`
}

// SessionDetailContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
type SessionDetailContentType string

// SessionDetailExpressionOutput defines model for SessionDetail.ExpressionOutput.
type SessionDetailExpressionOutput string

// SessionDetailSessionType defines model for SessionDetail.SessionType.
type SessionDetailSessionType string

// SessionDetailStatus defines model for SessionDetail.Status.
type SessionDetailStatus string

// SessionList defines model for SessionList.
type SessionList struct {
	HasMore  bool              `json:"has_more"`
	Limit    int               `json:"limit"`
	Offset   int               `json:"offset"`
	Sessions []SessionOverview `json:"sessions"`
}

// SessionOverview One home/resume row for the current user.
type SessionOverview struct {
	ArchivedAt  float64 `json:"archived_at,omitempty"`
	CompletedAt float64 `json:"completed_at,omitempty"`

	// ContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
	ContentType      SessionOverviewContentType      `json:"content_type"`
	CreatedAt        float64                         `json:"created_at"`
	ExpressionOutput SessionOverviewExpressionOutput `json:"expression_output,omitempty"`
	Language         string                          `json:"language"`
	Level            string                          `json:"level"`
	ReadingStartedAt float64                         `json:"reading_started_at,omitempty"`

	// SelectedCounts Persisted SelectedItems counts; background items are not currently stored.
	SelectedCounts SelectedItemCounts         `json:"selected_counts"`
	SessionId      string                     `json:"session_id"`
	SessionType    SessionOverviewSessionType `json:"session_type"`
	Status         SessionOverviewStatus      `json:"status"`

	// StoryId present once a story has been persisted for the session
	StoryId         string       `json:"story_id,omitempty"`
	Tasks           TaskProgress `json:"tasks"`
	Topic           string       `json:"topic,omitempty"`
	UserExpressions []string     `json:"user_expressions,omitempty"`
}

// SessionOverviewContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
type SessionOverviewContentType string

// SessionOverviewExpressionOutput defines model for SessionOverview.ExpressionOutput.
type SessionOverviewExpressionOutput string

// SessionOverviewSessionType defines model for SessionOverview.SessionType.
type SessionOverviewSessionType string

// SessionOverviewStatus defines model for SessionOverview.Status.
type SessionOverviewStatus string

// SessionRef defines model for SessionRef.
type SessionRef struct {
	SessionId string `json:"session_id"`
	Status    string `json:"status"`
}

// SessionTasks defines model for SessionTasks.
type SessionTasks struct {
	// Completed number of tasks already graded
	Completed int    `json:"completed"`
	SessionId string `json:"session_id"`
	Tasks     []Task `json:"tasks"`
	Total     int    `json:"total"`
}

// SkillCategory defines model for SkillCategory.
type SkillCategory struct {
	Id     string          `json:"id"`
	Skills []SkillProgress `json:"skills"`
	Title  string          `json:"title"`
}

// SkillProgress defines model for SkillProgress.
type SkillProgress struct {
	Category       string  `json:"category"`
	Description    string  `json:"description"`
	LastVerifiedAt float64 `json:"last_verified_at,omitempty"`
	Name           string  `json:"name"`

	// PendingVerification True when XP has crossed a tier boundary and AI verification has not completed.
	PendingVerification bool `json:"pending_verification"`

	// ProgressRatio Progress through the current tier as a 0..1 ratio.
	ProgressRatio float64 `json:"progress_ratio"`

	// RecentlyPromoted True shortly after a verified tier promotion.
	RecentlyPromoted bool   `json:"recently_promoted"`
	SkillId          string `json:"skill_id"`
	Tier             int    `json:"tier"`
	TierCount        int    `json:"tier_count"`

	// TierLabel Display label for the current tier, e.g. Not started, Introduced, Practicing, Acquired.
	TierLabel string  `json:"tier_label"`
	UpdatedAt float64 `json:"updated_at,omitempty"`
	Xp        int     `json:"xp"`
	XpPerTier int     `json:"xp_per_tier"`

	// XpToNext XP remaining before the next tier threshold; 0 at the max tier.
	XpToNext int `json:"xp_to_next"`
}

// SkillTree defines model for SkillTree.
type SkillTree struct {
	Categories []SkillCategory `json:"categories"`

	// Language Language code the skill tree is scoped to.
	Language string `json:"language"`
}

// SkillXPDelta defines model for SkillXPDelta.
type SkillXPDelta struct {
	// PendingVerify True when the skill crossed a tier threshold and awaits verification.
	PendingVerify bool   `json:"pending_verify"`
	SkillId       string `json:"skill_id"`
	TierAfter     int    `json:"tier_after"`
	TierBefore    int    `json:"tier_before"`
	XpAfter       int    `json:"xp_after"`
	XpBefore      int    `json:"xp_before"`
	XpDelta       int    `json:"xp_delta"`
}

// StageSummary defines model for StageSummary.
type StageSummary struct {
	ActiveStage string `json:"active_stage,omitempty"`
	Complete    int    `json:"complete"`
	Failed      int    `json:"failed"`
	FailedStage string `json:"failed_stage,omitempty"`
	InProgress  int    `json:"in_progress"`
	Pending     int    `json:"pending"`
	Total       int    `json:"total"`
}

// StartConversationRequest Greek is the fixed target language in the first release.
type StartConversationRequest struct {
	// Level Defaults to the learner profile level.
	Level StartConversationRequestLevel `json:"level,omitempty"`

	// SourceText Existing Greek story or other text to adapt into the lesson.
	SourceText string `json:"source_text,omitempty"`

	// Topic Learner-chosen subject that anchors the generated story.
	Topic string `json:"topic,omitempty"`
}

// StartConversationRequestLevel Defaults to the learner profile level.
type StartConversationRequestLevel string

// StoryContentRef Reference to a story session's story; load it via GET /stories/{id}.
type StoryContentRef struct {
	Language string `json:"language"`
	StoryId  string `json:"story_id"`
}

// StoryLoad Everything the reader needs at load time, in one response.
type StoryLoad struct {
	// Knowledge canonical key → canonical knowledge state; unseen items are absent
	Knowledge map[string]ReaderKnowledge `json:"knowledge"`
	Language  string                     `json:"language"`

	// Sentences Authoritative sentence spans for highlighting and sentence breakdown requests.
	Sentences []SentenceSpan `json:"sentences"`
	StoryId   string         `json:"story_id"`

	// SurfaceKnowledge StoryToken.form_key → exact-form level; unseen forms are absent
	SurfaceKnowledge map[string]ReaderSurfaceKnowledge `json:"surface_knowledge"`
	Tokens           []StoryToken                      `json:"tokens"`
}

// StoryToken One token of the server-tokenized story; non-word tokens carry no key.
type StoryToken struct {
	// FormKey opaque key used to look up this form in surface_knowledge
	FormKey string `json:"form_key,omitempty"`
	IsWord  bool   `json:"is_word"`

	// Key canonical knowledge key; omitted for non-word tokens
	Key string `json:"key,omitempty"`

	// Position 0-indexed, stable identifier
	Position int `json:"position"`

	// Surface display form incl. punctuation
	Surface string `json:"surface"`

	// SurfaceKey language-owned exact-form rating key; omitted for non-word tokens
	SurfaceKey string `json:"surface_key,omitempty"`
}

// SubmitTaskRequest defines model for SubmitTaskRequest.
type SubmitTaskRequest struct {
	// InputMethod property of the response; only "typed" supported today
	InputMethod SubmitTaskRequestInputMethod `json:"input_method,omitempty"`

	// ReferenceAssisted True when the answer followed an explicit story/reference peek.
	ReferenceAssisted bool `json:"reference_assisted,omitempty"`

	// Response type-specific response JSON (e.g. {selected_index}, {answer}, {text})
	Response map[string]interface{} `json:"response"`
}

// SubmitTaskRequestInputMethod property of the response; only "typed" supported today
type SubmitTaskRequestInputMethod string

// SubmitTaskResponse defines model for SubmitTaskResponse.
type SubmitTaskResponse struct {
	// AttemptCount How many times this task has been submitted (1 = first submission).
	AttemptCount int `json:"attempt_count"`

	// Grade The outcome of grading one task response.
	Grade Grade `json:"grade"`

	// ReferenceAssisted Persisted retrieval-integrity flag for this submission.
	ReferenceAssisted bool `json:"reference_assisted"`

	// SkillXp Skill XP deltas persisted for this accepted grade.
	SkillXp []SkillXPDelta `json:"skill_xp"`
	TaskId  string         `json:"task_id"`
}

// TargetPreview Selected targets and any ungraded preview attempts for this session.
type TargetPreview struct {
	Attempts []TargetPreviewAttempt `json:"attempts"`
	Items    []TargetPreviewItem    `json:"items"`
}

// TargetPreviewAttempt One ungraded warm-up attempt for a selected target item.
type TargetPreviewAttempt struct {
	// Correct Present only when correctness is computable without an LLM call.
	Correct   bool                   `json:"correct,omitempty"`
	CreatedAt float64                `json:"created_at"`
	GuessKind TargetPreviewGuessKind `json:"guess_kind"`
	GuessText string                 `json:"guess_text,omitempty"`
	ItemId    string                 `json:"item_id"`
	UpdatedAt float64                `json:"updated_at,omitempty"`
}

// TargetPreviewGuessKind defines model for TargetPreviewGuessKind.
type TargetPreviewGuessKind string

// TargetPreviewGuessRequest defines model for TargetPreviewGuessRequest.
type TargetPreviewGuessRequest struct {
	GuessKind TargetPreviewGuessKind `json:"guess_kind"`

	// GuessText Required when guess_kind is text; ignored for no_idea.
	GuessText string `json:"guess_text,omitempty"`
	ItemId    string `json:"item_id"`
}

// TargetPreviewItem A selected target item suitable for the generation warm-up.
type TargetPreviewItem struct {
	Display  string `json:"display"`
	ItemId   string `json:"item_id"`
	ItemType string `json:"item_type"`
	Key      string `json:"key"`
	Language string `json:"language"`
}

// Task One task in presentation form (answer-free content + grade once submitted).
type Task struct {
	// Content Present-filtered content — never includes answer keys.
	Content map[string]interface{} `json:"content"`
	Grade   *Grade                 `json:"grade,omitempty"`
	Graded  bool                   `json:"graded"`

	// ReferenceAssisted True when the submitted answer was marked as story/reference-assisted.
	ReferenceAssisted bool             `json:"reference_assisted"`
	Report            *TaskReportState `json:"report,omitempty"`
	TaskId            string           `json:"task_id"`

	// TaskType registered TaskType id
	TaskType string `json:"task_type"`
}

// TaskProgress defines model for TaskProgress.
type TaskProgress struct {
	// Completed number of tasks already graded
	Completed int `json:"completed"`
	Pending   int `json:"pending"`
	Total     int `json:"total"`
}

// TaskReportReason defines model for TaskReportReason.
type TaskReportReason string

// TaskReportRequest defines model for TaskReportRequest.
type TaskReportRequest struct {
	// Note Optional learner note explaining the defect.
	Note   string           `json:"note,omitempty"`
	Reason TaskReportReason `json:"reason"`
}

// TaskReportResponse defines model for TaskReportResponse.
type TaskReportResponse struct {
	Message           string `json:"message"`
	RegenerationCap   int    `json:"regeneration_cap"`
	RegenerationsUsed int    `json:"regenerations_used"`

	// ReplacementTaskId Present when regeneration has already produced or will update a task id.
	ReplacementTaskId string           `json:"replacement_task_id,omitempty"`
	ReportId          string           `json:"report_id"`
	Status            TaskReportStatus `json:"status"`
	TaskId            string           `json:"task_id"`
}

// TaskReportState Latest report/regeneration state for this task, if any.
type TaskReportState struct {
	Message           string           `json:"message"`
	Reason            TaskReportReason `json:"reason"`
	RegenerationCap   int              `json:"regeneration_cap"`
	RegenerationsUsed int              `json:"regenerations_used"`

	// ReplacementTaskId Task id containing the regenerated content; same as task_id when replacement is in place.
	ReplacementTaskId string           `json:"replacement_task_id,omitempty"`
	ReportId          string           `json:"report_id"`
	ReportedAt        float64          `json:"reported_at"`
	Status            TaskReportStatus `json:"status"`
	UpdatedAt         float64          `json:"updated_at,omitempty"`
}

// TaskReportStatus defines model for TaskReportStatus.
type TaskReportStatus string

// User defines model for User.
type User struct {
	CreatedAt float64 `json:"created_at"`
	Email     string  `json:"email"`
	LastLogin float64 `json:"last_login,omitempty"`
	UserId    string  `json:"user_id"`
}

// WordBreakdownTrace Word-specific breakdown trace metadata.
type WordBreakdownTrace struct {
	CanonicalKey string `json:"canonical_key"`
}

// WordKnowledgeRequest defines model for WordKnowledgeRequest.
type WordKnowledgeRequest struct {
	Language string `json:"language"`

	// Level '' clears to unseen
	Level WordKnowledgeRequestLevel `json:"level"`
}

// WordKnowledgeRequestLevel ” clears to unseen
type WordKnowledgeRequestLevel string

// SessionID defines model for SessionID.
type SessionID = string

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AdminListCallsParams defines parameters for AdminListCalls.
type AdminListCallsParams struct {
	UserId        string                     `form:"user_id,omitempty" json:"user_id,omitempty"`
	Model         string                     `form:"model,omitempty" json:"model,omitempty"`
	Kind          string                     `form:"kind,omitempty" json:"kind,omitempty"`
	Status        AdminListCallsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	PromptVersion string                     `form:"prompt_version,omitempty" json:"prompt_version,omitempty"`
	SessionId     string                     `form:"session_id,omitempty" json:"session_id,omitempty"`

	// From Lower bound (inclusive) on called_at, Unix seconds.
	From float64 `form:"from,omitempty" json:"from,omitempty"`

	// To Upper bound (exclusive) on called_at, Unix seconds.
	To     float64 `form:"to,omitempty" json:"to,omitempty"`
	Limit  int     `form:"limit,omitempty" json:"limit,omitempty"`
	Offset int     `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminListCallsParamsStatus defines parameters for AdminListCalls.
type AdminListCallsParamsStatus string

// AdminCostRollupParams defines parameters for AdminCostRollup.
type AdminCostRollupParams struct {
	// From Lower bound (inclusive) on called_at, Unix seconds.
	From float64 `form:"from,omitempty" json:"from,omitempty"`

	// To Upper bound (exclusive) on called_at, Unix seconds.
	To float64 `form:"to,omitempty" json:"to,omitempty"`
}

// GetConversationTurnAudioParams defines parameters for GetConversationTurnAudio.
type GetConversationTurnAudioParams struct {
	// Part Select the Greek passage or an English Full auto narration segment.
	Part GetConversationTurnAudioParamsPart `form:"part,omitempty" json:"part,omitempty"`
}

// GetConversationTurnAudioParamsPart defines parameters for GetConversationTurnAudio.
type GetConversationTurnAudioParamsPart string

// DeleteDictionaryEntryParams defines parameters for DeleteDictionaryEntry.
type DeleteDictionaryEntryParams struct {
	Language string `form:"language" json:"language"`

	// Key canonical knowledge key
	Key string `form:"key" json:"key"`
}

// GetDictionaryEntryParams defines parameters for GetDictionaryEntry.
type GetDictionaryEntryParams struct {
	Language string `form:"language" json:"language"`

	// Key canonical knowledge key
	Key string `form:"key" json:"key"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	Limit    int  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   int  `form:"offset,omitempty" json:"offset,omitempty"`
	Archived bool `form:"archived,omitempty" json:"archived,omitempty"`

	// Language registered language code to scope the page to; omitted lists all languages
	Language string `form:"language,omitempty" json:"language,omitempty"`
}

// ListSkillsParams defines parameters for ListSkills.
type ListSkillsParams struct {
	// Language Optional enabled language code; defaults to profile.active_language.
	Language string `form:"language,omitempty" json:"language,omitempty"`
}

// ListImportedStoriesParams defines parameters for ListImportedStories.
type ListImportedStoriesParams struct {
	Limit  int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset int `form:"offset,omitempty" json:"offset,omitempty"`

	// Language registered language code to scope the page to; omitted lists all languages
	Language string `form:"language,omitempty" json:"language,omitempty"`
}

// GetDefinitionParams defines parameters for GetDefinition.
type GetDefinitionParams struct {
	// Key canonical knowledge key to define
	Key string `form:"key" json:"key"`
}

// GetDefinitionOptionsParams defines parameters for GetDefinitionOptions.
type GetDefinitionOptionsParams struct {
	// Key canonical knowledge key to define
	Key string `form:"key" json:"key"`
}

// PostSentenceBreakdownJSONBody defines parameters for PostSentenceBreakdown.
type PostSentenceBreakdownJSONBody struct {
	Position int `json:"position"`
}

// GetStorySentenceAlignmentParams defines parameters for GetStorySentenceAlignment.
type GetStorySentenceAlignmentParams struct {
	// VoiceModel Client cache variant; authorization and the actual model remain server-owned.
	VoiceModel string `form:"voice_model,omitempty" json:"voice_model,omitempty"`
}

// GetStorySentenceAudioParams defines parameters for GetStorySentenceAudio.
type GetStorySentenceAudioParams struct {
	// VoiceModel Client cache variant; authorization and the actual model remain server-owned.
	VoiceModel string `form:"voice_model,omitempty" json:"voice_model,omitempty"`
}

// PostWordBreakdownJSONBody defines parameters for PostWordBreakdown.
type PostWordBreakdownJSONBody struct {
	Key string `json:"key"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Credentials

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = Credentials

// StartConversationJSONRequestBody defines body for StartConversation for application/json ContentType.
type StartConversationJSONRequestBody = StartConversationRequest

// RespondToConversationJSONRequestBody defines body for RespondToConversation for application/json ContentType.
type RespondToConversationJSONRequestBody = RespondConversationRequest

// RespondToConversationAudioMultipartRequestBody defines body for RespondToConversationAudio for multipart/form-data ContentType.
type RespondToConversationAudioMultipartRequestBody = ConversationAudioResponseRequest

// TranscribeConversationAudioMultipartRequestBody defines body for TranscribeConversationAudio for multipart/form-data ContentType.
type TranscribeConversationAudioMultipartRequestBody = ConversationAudioResponseRequest

// PutDictionaryEntryJSONRequestBody defines body for PutDictionaryEntry for application/json ContentType.
type PutDictionaryEntryJSONRequestBody = DictionaryEntryRequest

// PatchProfileJSONRequestBody defines body for PatchProfile for application/json ContentType.
type PatchProfileJSONRequestBody = ProfilePatch

// PostReaderEventsJSONRequestBody defines body for PostReaderEvents for application/json ContentType.
type PostReaderEventsJSONRequestBody = ReaderEventsRequest

// PutReaderSurfaceKnowledgeJSONRequestBody defines body for PutReaderSurfaceKnowledge for application/json ContentType.
type PutReaderSurfaceKnowledgeJSONRequestBody = ReaderSurfaceKnowledgeRequest

// GenerateSessionJSONRequestBody defines body for GenerateSession for application/json ContentType.
type GenerateSessionJSONRequestBody = GenerateRequest

// RecordTargetPreviewGuessJSONRequestBody defines body for RecordTargetPreviewGuess for application/json ContentType.
type RecordTargetPreviewGuessJSONRequestBody = TargetPreviewGuessRequest

// ImportStoryJSONRequestBody defines body for ImportStory for application/json ContentType.
type ImportStoryJSONRequestBody = ImportStoryRequest

// ImportStoryMultipartRequestBody defines body for ImportStory for multipart/form-data ContentType.
type ImportStoryMultipartRequestBody = ImportStoryUploadRequest

// PostSentenceBreakdownJSONRequestBody defines body for PostSentenceBreakdown for application/json ContentType.
type PostSentenceBreakdownJSONRequestBody PostSentenceBreakdownJSONBody

// PostWordBreakdownJSONRequestBody defines body for PostWordBreakdown for application/json ContentType.
type PostWordBreakdownJSONRequestBody PostWordBreakdownJSONBody

// ReportTaskJSONRequestBody defines body for ReportTask for application/json ContentType.
type ReportTaskJSONRequestBody = TaskReportRequest

// SubmitTaskJSONRequestBody defines body for SubmitTask for application/json ContentType.
type SubmitTaskJSONRequestBody = SubmitTaskRequest

// PutWordKnowledgeJSONRequestBody defines body for PutWordKnowledge for application/json ContentType.
type PutWordKnowledgeJSONRequestBody = WordKnowledgeRequest
