// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapigen

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for DefinitionSource.
const (
	DefinitionSourceGlossary             DefinitionSource = "glossary"
	DefinitionSourceLlm                  DefinitionSource = "llm"
	DefinitionSourceMetadata             DefinitionSource = "metadata"
	DefinitionSourceUser                 DefinitionSource = "user"
	DefinitionSourceWiktionary           DefinitionSource = "wiktionary"
	DefinitionSourceWiktionaryNative     DefinitionSource = "wiktionary-native"
	DefinitionSourceWiktionaryTranslated DefinitionSource = "wiktionary-translated"
)

// Valid indicates whether the value is a known member of the DefinitionSource enum.
func (e DefinitionSource) Valid() bool {
	switch e {
	case DefinitionSourceGlossary:
		return true
	case DefinitionSourceLlm:
		return true
	case DefinitionSourceMetadata:
		return true
	case DefinitionSourceUser:
		return true
	case DefinitionSourceWiktionary:
		return true
	case DefinitionSourceWiktionaryNative:
		return true
	case DefinitionSourceWiktionaryTranslated:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceWinningSource.
const (
	DefinitionTraceWinningSourceGlossary             DefinitionTraceWinningSource = "glossary"
	DefinitionTraceWinningSourceLlm                  DefinitionTraceWinningSource = "llm"
	DefinitionTraceWinningSourceMetadata             DefinitionTraceWinningSource = "metadata"
	DefinitionTraceWinningSourceUser                 DefinitionTraceWinningSource = "user"
	DefinitionTraceWinningSourceWiktionary           DefinitionTraceWinningSource = "wiktionary"
	DefinitionTraceWinningSourceWiktionaryNative     DefinitionTraceWinningSource = "wiktionary-native"
	DefinitionTraceWinningSourceWiktionaryTranslated DefinitionTraceWinningSource = "wiktionary-translated"
)

// Valid indicates whether the value is a known member of the DefinitionTraceWinningSource enum.
func (e DefinitionTraceWinningSource) Valid() bool {
	switch e {
	case DefinitionTraceWinningSourceGlossary:
		return true
	case DefinitionTraceWinningSourceLlm:
		return true
	case DefinitionTraceWinningSourceMetadata:
		return true
	case DefinitionTraceWinningSourceUser:
		return true
	case DefinitionTraceWinningSourceWiktionary:
		return true
	case DefinitionTraceWinningSourceWiktionaryNative:
		return true
	case DefinitionTraceWinningSourceWiktionaryTranslated:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceStepSource.
const (
	DefinitionTraceStepSourceGlossary             DefinitionTraceStepSource = "glossary"
	DefinitionTraceStepSourceLlm                  DefinitionTraceStepSource = "llm"
	DefinitionTraceStepSourceMetadata             DefinitionTraceStepSource = "metadata"
	DefinitionTraceStepSourceUser                 DefinitionTraceStepSource = "user"
	DefinitionTraceStepSourceWiktionary           DefinitionTraceStepSource = "wiktionary"
	DefinitionTraceStepSourceWiktionaryNative     DefinitionTraceStepSource = "wiktionary-native"
	DefinitionTraceStepSourceWiktionaryTranslated DefinitionTraceStepSource = "wiktionary-translated"
)

// Valid indicates whether the value is a known member of the DefinitionTraceStepSource enum.
func (e DefinitionTraceStepSource) Valid() bool {
	switch e {
	case DefinitionTraceStepSourceGlossary:
		return true
	case DefinitionTraceStepSourceLlm:
		return true
	case DefinitionTraceStepSourceMetadata:
		return true
	case DefinitionTraceStepSourceUser:
		return true
	case DefinitionTraceStepSourceWiktionary:
		return true
	case DefinitionTraceStepSourceWiktionaryNative:
		return true
	case DefinitionTraceStepSourceWiktionaryTranslated:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceStepStatus.
const (
	Hit     DefinitionTraceStepStatus = "hit"
	Miss    DefinitionTraceStepStatus = "miss"
	Skipped DefinitionTraceStepStatus = "skipped"
)

// Valid indicates whether the value is a known member of the DefinitionTraceStepStatus enum.
func (e DefinitionTraceStepStatus) Valid() bool {
	switch e {
	case Hit:
		return true
	case Miss:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for DefinitionTraceStepStep.
const (
	DefinitionTraceStepStepCanonicalKeyFollow DefinitionTraceStepStep = "canonical_key_follow"
	DefinitionTraceStepStepKnowledgeMetadata  DefinitionTraceStepStep = "knowledge_metadata"
	DefinitionTraceStepStepLlmFallback        DefinitionTraceStepStep = "llm_fallback"
	DefinitionTraceStepStepSharedCache        DefinitionTraceStepStep = "shared_cache"
	DefinitionTraceStepStepStoryGlossary      DefinitionTraceStepStep = "story_glossary"
	DefinitionTraceStepStepUserDictionary     DefinitionTraceStepStep = "user_dictionary"
	DefinitionTraceStepStepWiktionary         DefinitionTraceStepStep = "wiktionary"
)

// Valid indicates whether the value is a known member of the DefinitionTraceStepStep enum.
func (e DefinitionTraceStepStep) Valid() bool {
	switch e {
	case DefinitionTraceStepStepCanonicalKeyFollow:
		return true
	case DefinitionTraceStepStepKnowledgeMetadata:
		return true
	case DefinitionTraceStepStepLlmFallback:
		return true
	case DefinitionTraceStepStepSharedCache:
		return true
	case DefinitionTraceStepStepStoryGlossary:
		return true
	case DefinitionTraceStepStepUserDictionary:
		return true
	case DefinitionTraceStepStepWiktionary:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestExpressionOutput.
const (
	GenerateRequestExpressionOutputPhrases GenerateRequestExpressionOutput = "phrases"
	GenerateRequestExpressionOutputStory   GenerateRequestExpressionOutput = "story"
)

// Valid indicates whether the value is a known member of the GenerateRequestExpressionOutput enum.
func (e GenerateRequestExpressionOutput) Valid() bool {
	switch e {
	case GenerateRequestExpressionOutputPhrases:
		return true
	case GenerateRequestExpressionOutputStory:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestSessionType.
const (
	GenerateRequestSessionTypeExpressionGuided GenerateRequestSessionType = "expression_guided"
	GenerateRequestSessionTypeSystem           GenerateRequestSessionType = "system"
	GenerateRequestSessionTypeTopicGuided      GenerateRequestSessionType = "topic_guided"
)

// Valid indicates whether the value is a known member of the GenerateRequestSessionType enum.
func (e GenerateRequestSessionType) Valid() bool {
	switch e {
	case GenerateRequestSessionTypeExpressionGuided:
		return true
	case GenerateRequestSessionTypeSystem:
		return true
	case GenerateRequestSessionTypeTopicGuided:
		return true
	default:
		return false
	}
}

// Defines values for GenerationEventContentType.
const (
	GenerationEventContentTypePhraseSet GenerationEventContentType = "phrase_set"
	GenerationEventContentTypeStory     GenerationEventContentType = "story"
)

// Valid indicates whether the value is a known member of the GenerationEventContentType enum.
func (e GenerationEventContentType) Valid() bool {
	switch e {
	case GenerationEventContentTypePhraseSet:
		return true
	case GenerationEventContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for GenerationEventStatus.
const (
	GenerationEventStatusComplete   GenerationEventStatus = "complete"
	GenerationEventStatusFailed     GenerationEventStatus = "failed"
	GenerationEventStatusGenerating GenerationEventStatus = "generating"
	GenerationEventStatusInProgress GenerationEventStatus = "in_progress"
	GenerationEventStatusPending    GenerationEventStatus = "pending"
	GenerationEventStatusReading    GenerationEventStatus = "reading"
	GenerationEventStatusReady      GenerationEventStatus = "ready"
)

// Valid indicates whether the value is a known member of the GenerationEventStatus enum.
func (e GenerationEventStatus) Valid() bool {
	switch e {
	case GenerationEventStatusComplete:
		return true
	case GenerationEventStatusFailed:
		return true
	case GenerationEventStatusGenerating:
		return true
	case GenerationEventStatusInProgress:
		return true
	case GenerationEventStatusPending:
		return true
	case GenerationEventStatusReading:
		return true
	case GenerationEventStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStageRecordStatus.
const (
	GenerationStageRecordStatusComplete   GenerationStageRecordStatus = "complete"
	GenerationStageRecordStatusFailed     GenerationStageRecordStatus = "failed"
	GenerationStageRecordStatusInProgress GenerationStageRecordStatus = "in_progress"
	GenerationStageRecordStatusPending    GenerationStageRecordStatus = "pending"
)

// Valid indicates whether the value is a known member of the GenerationStageRecordStatus enum.
func (e GenerationStageRecordStatus) Valid() bool {
	switch e {
	case GenerationStageRecordStatusComplete:
		return true
	case GenerationStageRecordStatusFailed:
		return true
	case GenerationStageRecordStatusInProgress:
		return true
	case GenerationStageRecordStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for GradeGradedBy.
const (
	Llm  GradeGradedBy = "llm"
	Rule GradeGradedBy = "rule"
)

// Valid indicates whether the value is a known member of the GradeGradedBy enum.
func (e GradeGradedBy) Valid() bool {
	switch e {
	case Llm:
		return true
	case Rule:
		return true
	default:
		return false
	}
}

// Defines values for LLMCallStatus.
const (
	Error   LLMCallStatus = "error"
	Success LLMCallStatus = "success"
	Timeout LLMCallStatus = "timeout"
)

// Valid indicates whether the value is a known member of the LLMCallStatus enum.
func (e LLMCallStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Success:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// Defines values for LanguageKeyStrategy.
const (
	Lemma   LanguageKeyStrategy = "lemma"
	Root    LanguageKeyStrategy = "root"
	Stem    LanguageKeyStrategy = "stem"
	Surface LanguageKeyStrategy = "surface"
)

// Valid indicates whether the value is a known member of the LanguageKeyStrategy enum.
func (e LanguageKeyStrategy) Valid() bool {
	switch e {
	case Lemma:
		return true
	case Root:
		return true
	case Stem:
		return true
	case Surface:
		return true
	default:
		return false
	}
}

// Defines values for ProfileLevel.
const (
	ProfileLevelAdvanced          ProfileLevel = "advanced"
	ProfileLevelBeginner          ProfileLevel = "beginner"
	ProfileLevelElementary        ProfileLevel = "elementary"
	ProfileLevelIntermediate      ProfileLevel = "intermediate"
	ProfileLevelUpperIntermediate ProfileLevel = "upper-intermediate"
)

// Valid indicates whether the value is a known member of the ProfileLevel enum.
func (e ProfileLevel) Valid() bool {
	switch e {
	case ProfileLevelAdvanced:
		return true
	case ProfileLevelBeginner:
		return true
	case ProfileLevelElementary:
		return true
	case ProfileLevelIntermediate:
		return true
	case ProfileLevelUpperIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for ProfilePatchLevel.
const (
	ProfilePatchLevelAdvanced          ProfilePatchLevel = "advanced"
	ProfilePatchLevelBeginner          ProfilePatchLevel = "beginner"
	ProfilePatchLevelElementary        ProfilePatchLevel = "elementary"
	ProfilePatchLevelIntermediate      ProfilePatchLevel = "intermediate"
	ProfilePatchLevelUpperIntermediate ProfilePatchLevel = "upper-intermediate"
)

// Valid indicates whether the value is a known member of the ProfilePatchLevel enum.
func (e ProfilePatchLevel) Valid() bool {
	switch e {
	case ProfilePatchLevelAdvanced:
		return true
	case ProfilePatchLevelBeginner:
		return true
	case ProfilePatchLevelElementary:
		return true
	case ProfilePatchLevelIntermediate:
		return true
	case ProfilePatchLevelUpperIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for ReaderEventEventType.
const (
	Lookup        ReaderEventEventType = "lookup"
	Navigate      ReaderEventEventType = "navigate"
	Rate          ReaderEventEventType = "rate"
	SentenceBreak ReaderEventEventType = "sentence_break"
)

// Valid indicates whether the value is a known member of the ReaderEventEventType enum.
func (e ReaderEventEventType) Valid() bool {
	switch e {
	case Lookup:
		return true
	case Navigate:
		return true
	case Rate:
		return true
	case SentenceBreak:
		return true
	default:
		return false
	}
}

// Defines values for ReaderKnowledgeLevel.
const (
	ReaderKnowledgeLevelEmpty     ReaderKnowledgeLevel = ""
	ReaderKnowledgeLevelIgnored   ReaderKnowledgeLevel = "ignored"
	ReaderKnowledgeLevelN1        ReaderKnowledgeLevel = "1"
	ReaderKnowledgeLevelN2        ReaderKnowledgeLevel = "2"
	ReaderKnowledgeLevelN3        ReaderKnowledgeLevel = "3"
	ReaderKnowledgeLevelN4        ReaderKnowledgeLevel = "4"
	ReaderKnowledgeLevelN5        ReaderKnowledgeLevel = "5"
	ReaderKnowledgeLevelWellKnown ReaderKnowledgeLevel = "well_known"
)

// Valid indicates whether the value is a known member of the ReaderKnowledgeLevel enum.
func (e ReaderKnowledgeLevel) Valid() bool {
	switch e {
	case ReaderKnowledgeLevelEmpty:
		return true
	case ReaderKnowledgeLevelIgnored:
		return true
	case ReaderKnowledgeLevelN1:
		return true
	case ReaderKnowledgeLevelN2:
		return true
	case ReaderKnowledgeLevelN3:
		return true
	case ReaderKnowledgeLevelN4:
		return true
	case ReaderKnowledgeLevelN5:
		return true
	case ReaderKnowledgeLevelWellKnown:
		return true
	default:
		return false
	}
}

// Defines values for ReaderSurfaceKnowledgeLevel.
const (
	ReaderSurfaceKnowledgeLevelEmpty     ReaderSurfaceKnowledgeLevel = ""
	ReaderSurfaceKnowledgeLevelIgnored   ReaderSurfaceKnowledgeLevel = "ignored"
	ReaderSurfaceKnowledgeLevelN1        ReaderSurfaceKnowledgeLevel = "1"
	ReaderSurfaceKnowledgeLevelN2        ReaderSurfaceKnowledgeLevel = "2"
	ReaderSurfaceKnowledgeLevelN3        ReaderSurfaceKnowledgeLevel = "3"
	ReaderSurfaceKnowledgeLevelN4        ReaderSurfaceKnowledgeLevel = "4"
	ReaderSurfaceKnowledgeLevelN5        ReaderSurfaceKnowledgeLevel = "5"
	ReaderSurfaceKnowledgeLevelWellKnown ReaderSurfaceKnowledgeLevel = "well_known"
)

// Valid indicates whether the value is a known member of the ReaderSurfaceKnowledgeLevel enum.
func (e ReaderSurfaceKnowledgeLevel) Valid() bool {
	switch e {
	case ReaderSurfaceKnowledgeLevelEmpty:
		return true
	case ReaderSurfaceKnowledgeLevelIgnored:
		return true
	case ReaderSurfaceKnowledgeLevelN1:
		return true
	case ReaderSurfaceKnowledgeLevelN2:
		return true
	case ReaderSurfaceKnowledgeLevelN3:
		return true
	case ReaderSurfaceKnowledgeLevelN4:
		return true
	case ReaderSurfaceKnowledgeLevelN5:
		return true
	case ReaderSurfaceKnowledgeLevelWellKnown:
		return true
	default:
		return false
	}
}

// Defines values for ReaderSurfaceKnowledgeRequestLevel.
const (
	ReaderSurfaceKnowledgeRequestLevelEmpty     ReaderSurfaceKnowledgeRequestLevel = ""
	ReaderSurfaceKnowledgeRequestLevelIgnored   ReaderSurfaceKnowledgeRequestLevel = "ignored"
	ReaderSurfaceKnowledgeRequestLevelN1        ReaderSurfaceKnowledgeRequestLevel = "1"
	ReaderSurfaceKnowledgeRequestLevelN2        ReaderSurfaceKnowledgeRequestLevel = "2"
	ReaderSurfaceKnowledgeRequestLevelN3        ReaderSurfaceKnowledgeRequestLevel = "3"
	ReaderSurfaceKnowledgeRequestLevelN4        ReaderSurfaceKnowledgeRequestLevel = "4"
	ReaderSurfaceKnowledgeRequestLevelN5        ReaderSurfaceKnowledgeRequestLevel = "5"
	ReaderSurfaceKnowledgeRequestLevelWellKnown ReaderSurfaceKnowledgeRequestLevel = "well_known"
)

// Valid indicates whether the value is a known member of the ReaderSurfaceKnowledgeRequestLevel enum.
func (e ReaderSurfaceKnowledgeRequestLevel) Valid() bool {
	switch e {
	case ReaderSurfaceKnowledgeRequestLevelEmpty:
		return true
	case ReaderSurfaceKnowledgeRequestLevelIgnored:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN1:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN2:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN3:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN4:
		return true
	case ReaderSurfaceKnowledgeRequestLevelN5:
		return true
	case ReaderSurfaceKnowledgeRequestLevelWellKnown:
		return true
	default:
		return false
	}
}

// Defines values for SessionContentContentType.
const (
	SessionContentContentTypePhraseSet SessionContentContentType = "phrase_set"
	SessionContentContentTypeStory     SessionContentContentType = "story"
)

// Valid indicates whether the value is a known member of the SessionContentContentType enum.
func (e SessionContentContentType) Valid() bool {
	switch e {
	case SessionContentContentTypePhraseSet:
		return true
	case SessionContentContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailContentType.
const (
	SessionDetailContentTypePhraseSet SessionDetailContentType = "phrase_set"
	SessionDetailContentTypeStory     SessionDetailContentType = "story"
)

// Valid indicates whether the value is a known member of the SessionDetailContentType enum.
func (e SessionDetailContentType) Valid() bool {
	switch e {
	case SessionDetailContentTypePhraseSet:
		return true
	case SessionDetailContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailExpressionOutput.
const (
	SessionDetailExpressionOutputPhrases SessionDetailExpressionOutput = "phrases"
	SessionDetailExpressionOutputStory   SessionDetailExpressionOutput = "story"
)

// Valid indicates whether the value is a known member of the SessionDetailExpressionOutput enum.
func (e SessionDetailExpressionOutput) Valid() bool {
	switch e {
	case SessionDetailExpressionOutputPhrases:
		return true
	case SessionDetailExpressionOutputStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailSessionType.
const (
	SessionDetailSessionTypeExpressionGuided SessionDetailSessionType = "expression_guided"
	SessionDetailSessionTypeSystem           SessionDetailSessionType = "system"
	SessionDetailSessionTypeTopicGuided      SessionDetailSessionType = "topic_guided"
)

// Valid indicates whether the value is a known member of the SessionDetailSessionType enum.
func (e SessionDetailSessionType) Valid() bool {
	switch e {
	case SessionDetailSessionTypeExpressionGuided:
		return true
	case SessionDetailSessionTypeSystem:
		return true
	case SessionDetailSessionTypeTopicGuided:
		return true
	default:
		return false
	}
}

// Defines values for SessionDetailStatus.
const (
	SessionDetailStatusComplete   SessionDetailStatus = "complete"
	SessionDetailStatusFailed     SessionDetailStatus = "failed"
	SessionDetailStatusGenerating SessionDetailStatus = "generating"
	SessionDetailStatusPending    SessionDetailStatus = "pending"
	SessionDetailStatusReading    SessionDetailStatus = "reading"
	SessionDetailStatusReady      SessionDetailStatus = "ready"
)

// Valid indicates whether the value is a known member of the SessionDetailStatus enum.
func (e SessionDetailStatus) Valid() bool {
	switch e {
	case SessionDetailStatusComplete:
		return true
	case SessionDetailStatusFailed:
		return true
	case SessionDetailStatusGenerating:
		return true
	case SessionDetailStatusPending:
		return true
	case SessionDetailStatusReading:
		return true
	case SessionDetailStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewContentType.
const (
	SessionOverviewContentTypePhraseSet SessionOverviewContentType = "phrase_set"
	SessionOverviewContentTypeStory     SessionOverviewContentType = "story"
)

// Valid indicates whether the value is a known member of the SessionOverviewContentType enum.
func (e SessionOverviewContentType) Valid() bool {
	switch e {
	case SessionOverviewContentTypePhraseSet:
		return true
	case SessionOverviewContentTypeStory:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewExpressionOutput.
const (
	Phrases SessionOverviewExpressionOutput = "phrases"
	Story   SessionOverviewExpressionOutput = "story"
)

// Valid indicates whether the value is a known member of the SessionOverviewExpressionOutput enum.
func (e SessionOverviewExpressionOutput) Valid() bool {
	switch e {
	case Phrases:
		return true
	case Story:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewSessionType.
const (
	ExpressionGuided SessionOverviewSessionType = "expression_guided"
	System           SessionOverviewSessionType = "system"
	TopicGuided      SessionOverviewSessionType = "topic_guided"
)

// Valid indicates whether the value is a known member of the SessionOverviewSessionType enum.
func (e SessionOverviewSessionType) Valid() bool {
	switch e {
	case ExpressionGuided:
		return true
	case System:
		return true
	case TopicGuided:
		return true
	default:
		return false
	}
}

// Defines values for SessionOverviewStatus.
const (
	SessionOverviewStatusComplete   SessionOverviewStatus = "complete"
	SessionOverviewStatusFailed     SessionOverviewStatus = "failed"
	SessionOverviewStatusGenerating SessionOverviewStatus = "generating"
	SessionOverviewStatusPending    SessionOverviewStatus = "pending"
	SessionOverviewStatusReading    SessionOverviewStatus = "reading"
	SessionOverviewStatusReady      SessionOverviewStatus = "ready"
)

// Valid indicates whether the value is a known member of the SessionOverviewStatus enum.
func (e SessionOverviewStatus) Valid() bool {
	switch e {
	case SessionOverviewStatusComplete:
		return true
	case SessionOverviewStatusFailed:
		return true
	case SessionOverviewStatusGenerating:
		return true
	case SessionOverviewStatusPending:
		return true
	case SessionOverviewStatusReading:
		return true
	case SessionOverviewStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for SubmitTaskRequestInputMethod.
const (
	Typed SubmitTaskRequestInputMethod = "typed"
)

// Valid indicates whether the value is a known member of the SubmitTaskRequestInputMethod enum.
func (e SubmitTaskRequestInputMethod) Valid() bool {
	switch e {
	case Typed:
		return true
	default:
		return false
	}
}

// Defines values for WordKnowledgeRequestLevel.
const (
	WordKnowledgeRequestLevelEmpty     WordKnowledgeRequestLevel = ""
	WordKnowledgeRequestLevelIgnored   WordKnowledgeRequestLevel = "ignored"
	WordKnowledgeRequestLevelN1        WordKnowledgeRequestLevel = "1"
	WordKnowledgeRequestLevelN2        WordKnowledgeRequestLevel = "2"
	WordKnowledgeRequestLevelN3        WordKnowledgeRequestLevel = "3"
	WordKnowledgeRequestLevelN4        WordKnowledgeRequestLevel = "4"
	WordKnowledgeRequestLevelN5        WordKnowledgeRequestLevel = "5"
	WordKnowledgeRequestLevelWellKnown WordKnowledgeRequestLevel = "well_known"
)

// Valid indicates whether the value is a known member of the WordKnowledgeRequestLevel enum.
func (e WordKnowledgeRequestLevel) Valid() bool {
	switch e {
	case WordKnowledgeRequestLevelEmpty:
		return true
	case WordKnowledgeRequestLevelIgnored:
		return true
	case WordKnowledgeRequestLevelN1:
		return true
	case WordKnowledgeRequestLevelN2:
		return true
	case WordKnowledgeRequestLevelN3:
		return true
	case WordKnowledgeRequestLevelN4:
		return true
	case WordKnowledgeRequestLevelN5:
		return true
	case WordKnowledgeRequestLevelWellKnown:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
	User        User   `json:"user"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Definition A resolved word definition for the reader popup.
type Definition struct {
	Etymology       string `json:"etymology,omitempty"`
	Example         string `json:"example,omitempty"`
	Gloss           string `json:"gloss"`
	GrammaticalNote string `json:"grammatical_note,omitempty"`
	Key             string `json:"key"`
	Notes           string `json:"notes,omitempty"`

	// Source where the definition came from
	Source DefinitionSource `json:"source"`

	// Trace Debug-safe source trace for a reader definition lookup.
	Trace DefinitionTrace `json:"trace"`
}

// DefinitionSource where the definition came from
type DefinitionSource string

// DefinitionTrace Debug-safe source trace for a reader definition lookup.
type DefinitionTrace struct {
	QueryKey      string                       `json:"query_key"`
	ResolvedKey   string                       `json:"resolved_key"`
	Steps         []DefinitionTraceStep        `json:"steps"`
	WinningSource DefinitionTraceWinningSource `json:"winning_source"`
}

// DefinitionTraceWinningSource defines model for DefinitionTrace.WinningSource.
type DefinitionTraceWinningSource string

// DefinitionTraceStep One checked source in the ordered definition lookup chain.
type DefinitionTraceStep struct {
	Count     int                       `json:"count,omitempty"`
	Key       string                    `json:"key,omitempty"`
	Reason    string                    `json:"reason,omitempty"`
	Source    DefinitionTraceStepSource `json:"source,omitempty"`
	Status    DefinitionTraceStepStatus `json:"status"`
	Step      DefinitionTraceStepStep   `json:"step"`
	TargetKey string                    `json:"target_key,omitempty"`
}

// DefinitionTraceStepSource defines model for DefinitionTraceStep.Source.
type DefinitionTraceStepSource string

// DefinitionTraceStepStatus defines model for DefinitionTraceStep.Status.
type DefinitionTraceStepStatus string

// DefinitionTraceStepStep defines model for DefinitionTraceStep.Step.
type DefinitionTraceStepStep string

// DictionaryEntry A caller-owned dictionary override for one canonical word key.
type DictionaryEntry struct {
	Gloss    string `json:"gloss"`
	Key      string `json:"key"`
	Language string `json:"language"`
	Notes    string `json:"notes,omitempty"`
}

// DictionaryEntryRequest defines model for DictionaryEntryRequest.
type DictionaryEntryRequest struct {
	Gloss string `json:"gloss"`

	// Key canonical knowledge key
	Key      string `json:"key"`
	Language string `json:"language"`
	Notes    string `json:"notes,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// ExpressionOutput expression_guided only
	ExpressionOutput GenerateRequestExpressionOutput `json:"expression_output,omitempty"`

	// Language registered enabled language code, e.g. 'el'; defaults to profile.active_language
	Language string `json:"language,omitempty"`

	// Level beginner|elementary|intermediate|upper-intermediate|advanced; defaults to derived verified skill level when available, otherwise profile.level
	Level       string                     `json:"level,omitempty"`
	SessionType GenerateRequestSessionType `json:"session_type,omitempty"`

	// Topic topic_guided only
	Topic string `json:"topic,omitempty"`

	// UserExpressions expression_guided only
	UserExpressions []string `json:"user_expressions,omitempty"`
}

// GenerateRequestExpressionOutput expression_guided only
type GenerateRequestExpressionOutput string

// GenerateRequestSessionType defines model for GenerateRequest.SessionType.
type GenerateRequestSessionType string

// GenerationEvent One SSE progress message (the JSON in each data line). Non-terminal events report a pipeline stage status. The terminal `stage: done` event reports the final session status plus enough persisted state for the client to navigate to reader/tasks or show retry/error UI without guessing.
type GenerationEvent struct {
	// ContentType present on stage=done; whether the session produced a story (load via /stories/{id}) or a phrase set (load via /sessions/{id}/content)
	ContentType GenerationEventContentType `json:"content_type,omitempty"`

	// ErrorCode stable code on failed progress events and failed terminal events; GEN_SCOPE_REJECTED means a topic-guided topic was out of scope for the learner level
	ErrorCode string `json:"error_code,omitempty"`

	// ErrorDetail human-readable failure reason on failed terminal events, e.g. why a topic was rejected and an optional simpler rephrasing to try
	ErrorDetail string `json:"error_detail,omitempty"`

	// FailedStage first failed stage, present on failed terminal events
	FailedStage string `json:"failed_stage,omitempty"`

	// SessionId present on stage=done
	SessionId string `json:"session_id,omitempty"`

	// Stage scope_check|selection|story_generation|phrase_generation|tokenization|task_<type>|done
	Stage        string       `json:"stage"`
	StageSummary StageSummary `json:"stage_summary,omitempty"`

	// Status stage status for progress events; final session status for stage=done
	Status GenerationEventStatus `json:"status,omitempty"`

	// StoryId present on stage=done once a story has been persisted
	StoryId string       `json:"story_id,omitempty"`
	Tasks   TaskProgress `json:"tasks,omitempty"`

	// TokenRate approx upstream tokens/sec
	TokenRate int `json:"token_rate,omitempty"`
}

// GenerationEventContentType present on stage=done; whether the session produced a story (load via /stories/{id}) or a phrase set (load via /sessions/{id}/content)
type GenerationEventContentType string

// GenerationEventStatus stage status for progress events; final session status for stage=done
type GenerationEventStatus string

// GenerationStageRecord defines model for GenerationStageRecord.
type GenerationStageRecord struct {
	CompletedAt float64                     `json:"completed_at,omitempty"`
	ErrorCode   string                      `json:"error_code,omitempty"`
	ErrorDetail string                      `json:"error_detail,omitempty"`
	RetryCount  int                         `json:"retry_count"`
	Stage       string                      `json:"stage"`
	StartedAt   float64                     `json:"started_at,omitempty"`
	Status      GenerationStageRecordStatus `json:"status"`
}

// GenerationStageRecordStatus defines model for GenerationStageRecord.Status.
type GenerationStageRecordStatus string

// Grade The outcome of grading one task response.
type Grade struct {
	Correct  bool          `json:"correct"`
	Feedback string        `json:"feedback,omitempty"`
	GradedBy GradeGradedBy `json:"graded_by"`

	// ItemsDemonstrated knowledge item ids the response demonstrated
	ItemsDemonstrated []string `json:"items_demonstrated,omitempty"`

	// Score 0.0..1.0
	Score float64 `json:"score"`
}

// GradeGradedBy defines model for Grade.GradedBy.
type GradeGradedBy string

// ImportStoryRequest defines model for ImportStoryRequest.
type ImportStoryRequest struct {
	// Language registered enabled language code, e.g. 'el'; defaults to profile.active_language
	Language string `json:"language,omitempty"`

	// Level beginner|elementary|intermediate|upper-intermediate|advanced; defaults to profile.level
	Level string `json:"level,omitempty"`

	// Text raw target-language text to tokenize for the reader
	Text string `json:"text"`

	// Title optional user-facing label stored as imported-story metadata
	Title string `json:"title,omitempty"`
}

// ImportStoryResponse defines model for ImportStoryResponse.
type ImportStoryResponse struct {
	Language string `json:"language"`
	StoryId  string `json:"story_id"`
	Title    string `json:"title,omitempty"`
}

// ImportStoryUploadRequest defines model for ImportStoryUploadRequest.
type ImportStoryUploadRequest struct {
	// File UTF-8 text/plain .txt file, at most 512 KiB
	File openapi_types.File `json:"file"`

	// Language registered enabled language code, e.g. 'el'; defaults to profile.active_language
	Language string `json:"language,omitempty"`

	// Level beginner|elementary|intermediate|upper-intermediate|advanced; defaults to profile.level
	Level string `json:"level,omitempty"`

	// Title optional user-facing label stored as imported-story metadata
	Title string `json:"title,omitempty"`
}

// LLMCall One llm_calls audit row scoped to a session and current user.
type LLMCall struct {
	CallId      string  `json:"call_id"`
	CalledAt    float64 `json:"called_at"`
	ErrorDetail string  `json:"error_detail,omitempty"`

	// ErrorPayload Raw gateway error response body when available.
	ErrorPayload string `json:"error_payload,omitempty"`
	InputTokens  int    `json:"input_tokens,omitempty"`
	Kind         string `json:"kind"`
	LatencyMs    int    `json:"latency_ms,omitempty"`
	Model        string `json:"model"`
	OutputTokens int    `json:"output_tokens,omitempty"`

	// ParsedOutput Assistant content extracted from the provider envelope when available. If no separate parsed payload exists for a call, clients should use raw_response for debugging.
	ParsedOutput  string `json:"parsed_output,omitempty"`
	PromptVersion string `json:"prompt_version"`

	// RawResponse Raw gateway response body. On successful calls this is the provider envelope.
	RawResponse string        `json:"raw_response,omitempty"`
	SessionId   string        `json:"session_id,omitempty"`
	Status      LLMCallStatus `json:"status"`

	// SystemPrompt System prompt sent to the LLM gateway when present.
	SystemPrompt string `json:"system_prompt,omitempty"`
	UserId       string `json:"user_id,omitempty"`

	// UserPrompt User prompt sent to the LLM gateway.
	UserPrompt string `json:"user_prompt,omitempty"`
}

// LLMCallStatus defines model for LLMCall.Status.
type LLMCallStatus string

// LLMModel defines model for LLMModel.
type LLMModel struct {
	// ContextLength Maximum context length when provided by the upstream.
	ContextLength int `json:"context_length,omitempty"`

	// Description Upstream model description.
	Description string `json:"description,omitempty"`

	// Id Provider model id.
	Id string `json:"id"`

	// Name Display name when provided by the upstream.
	Name string `json:"name,omitempty"`
}

// Language defines model for Language.
type Language struct {
	Code        string              `json:"code"`
	Enabled     bool                `json:"enabled"`
	KeyStrategy LanguageKeyStrategy `json:"key_strategy"`
	Name        string              `json:"name"`
}

// LanguageKeyStrategy defines model for Language.KeyStrategy.
type LanguageKeyStrategy string

// PhraseAnnotation defines model for PhraseAnnotation.
type PhraseAnnotation struct {
	// Kind e.g. construction | vocabulary
	Kind  string `json:"kind"`
	Label string `json:"label,omitempty"`
	Note  string `json:"note,omitempty"`
}

// PhraseItem One phrase plus the annotations that explain what it teaches.
type PhraseItem struct {
	Annotations []PhraseAnnotation `json:"annotations,omitempty"`

	// Gloss English translation
	Gloss    string `json:"gloss,omitempty"`
	Notes    string `json:"notes,omitempty"`
	PhraseId string `json:"phrase_id"`

	// TargetItemIds knowledge item ids this phrase practises
	TargetItemIds []string `json:"target_item_ids,omitempty"`

	// TargetText the target-language phrase
	TargetText string `json:"target_text"`
}

// PhraseSet The content of an expression-guided phrase session.
type PhraseSet struct {
	Items     []PhraseItem `json:"items"`
	Language  string       `json:"language"`
	SessionId string       `json:"session_id"`
}

// Profile defines model for Profile.
type Profile struct {
	// ActiveLanguage enabled language code used when generation omits language
	ActiveLanguage string `json:"active_language"`

	// Level stored level fallback; session generation may derive a fresher value from verified skill tiers
	Level ProfileLevel `json:"level"`

	// LlmModel model id requested for LLM calls; blank uses the gateway default
	LlmModel string `json:"llm_model"`

	// Preferences arbitrary client-owned preferences; product-critical fields remain top-level
	Preferences map[string]interface{} `json:"preferences"`

	// Theme theme id, e.g. 'default' or 'high-contrast'
	Theme string `json:"theme"`

	// UiLanguage BCP-47 style UI/gloss language tag, e.g. 'en'
	UiLanguage string `json:"ui_language"`
	UserId     string `json:"user_id"`
}

// ProfileLevel stored level fallback; session generation may derive a fresher value from verified skill tiers
type ProfileLevel string

// ProfilePatch defines model for ProfilePatch.
type ProfilePatch struct {
	// ActiveLanguage must name an enabled language
	ActiveLanguage string `json:"active_language,omitempty"`

	// Level stored level fallback; clients should not treat this as arbitrary preference state
	Level ProfilePatchLevel `json:"level,omitempty"`

	// LlmModel OpenAI/OpenRouter-compatible model id; empty string clears to the gateway default
	LlmModel string `json:"llm_model,omitempty"`

	// Preferences shallow-merged; null values delete keys
	Preferences map[string]interface{} `json:"preferences,omitempty"`

	// Theme letters, numbers, '_' and '-' only
	Theme string `json:"theme,omitempty"`

	// UiLanguage BCP-47 style UI/gloss language tag
	UiLanguage string `json:"ui_language,omitempty"`
}

// ProfilePatchLevel stored level fallback; clients should not treat this as arbitrary preference state
type ProfilePatchLevel string

// ReaderEvent One logged reader interaction.
type ReaderEvent struct {
	// EventId client idempotency key; generated if omitted
	EventId   string               `json:"event_id,omitempty"`
	EventType ReaderEventEventType `json:"event_type"`

	// OccurredAt Unix seconds (client clock)
	OccurredAt float64 `json:"occurred_at,omitempty"`

	// Position story token position the event is about
	Position  int    `json:"position,omitempty"`
	SessionId string `json:"session_id,omitempty"`
	StoryId   string `json:"story_id"`

	// Value rate only: "1".."5" | "w" | "i"
	Value string `json:"value,omitempty"`
}

// ReaderEventEventType defines model for ReaderEvent.EventType.
type ReaderEventEventType string

// ReaderEventsRequest defines model for ReaderEventsRequest.
type ReaderEventsRequest struct {
	Events []ReaderEvent `json:"events"`
}

// ReaderKnowledge The reader's canonical per-item view, keyed by lemma/root/stem key.
type ReaderKnowledge struct {
	// Level explicit canonical learner mark; '' (omitted)=none
	Level       ReaderKnowledgeLevel `json:"level"`
	LookupCount int                  `json:"lookup_count"`
}

// ReaderKnowledgeLevel explicit canonical learner mark; ” (omitted)=none
type ReaderKnowledgeLevel string

// ReaderSurfaceKnowledge The reader's per-displayed-form level, keyed by StoryToken.form_key.
type ReaderSurfaceKnowledge struct {
	// Level learner self-rating for this exact form; ''=unseen
	Level ReaderSurfaceKnowledgeLevel `json:"level"`
}

// ReaderSurfaceKnowledgeLevel learner self-rating for this exact form; ”=unseen
type ReaderSurfaceKnowledgeLevel string

// ReaderSurfaceKnowledgeRequest defines model for ReaderSurfaceKnowledgeRequest.
type ReaderSurfaceKnowledgeRequest struct {
	// ItemKey canonical lemma/root/stem key for the token
	ItemKey  string `json:"item_key"`
	Language string `json:"language"`

	// Level '' clears to unseen for this exact form
	Level ReaderSurfaceKnowledgeRequestLevel `json:"level"`

	// SurfaceKey StoryToken.surface_key for the displayed form
	SurfaceKey string `json:"surface_key"`
}

// ReaderSurfaceKnowledgeRequestLevel ” clears to unseen for this exact form
type ReaderSurfaceKnowledgeRequestLevel string

// SelectedItemCounts Persisted SelectedItems counts; background items are not currently stored.
type SelectedItemCounts struct {
	New     int `json:"new"`
	Targets int `json:"targets"`
}

// SentenceSpan Authoritative sentence boundary over story token positions. Positions are half-open: tokens with position >= start_position and < end_position are part of the sentence. Text is exactly the sentence text used by the sentence-breakdown cache key.
type SentenceSpan struct {
	// EndPosition One past the final token position in the sentence.
	EndPosition int `json:"end_position"`

	// Index 0-indexed sentence number within the story.
	Index int `json:"index"`

	// StartPosition First token position in the sentence, inclusive.
	StartPosition int `json:"start_position"`

	// Text Readable sentence text reconstructed from story tokens.
	Text string `json:"text"`
}

// SessionContent A session's content, discriminated by content_type. Exactly one of story or phrase_set is present.
type SessionContent struct {
	ContentType SessionContentContentType `json:"content_type"`

	// PhraseSet The content of an expression-guided phrase session.
	PhraseSet PhraseSet `json:"phrase_set,omitempty"`
	SessionId string    `json:"session_id"`

	// Story Reference to a story session's story; load it via GET /stories/{id}.
	Story StoryContentRef `json:"story,omitempty"`
}

// SessionContentContentType defines model for SessionContent.ContentType.
type SessionContentContentType string

// SessionDebug defines model for SessionDebug.
type SessionDebug struct {
	LlmCalls []LLMCall     `json:"llm_calls"`
	Session  SessionDetail `json:"session"`
}

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	ArchivedAt  float64 `json:"archived_at,omitempty"`
	CompletedAt float64 `json:"completed_at,omitempty"`

	// ContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
	ContentType      SessionDetailContentType      `json:"content_type"`
	CreatedAt        float64                       `json:"created_at"`
	ExpressionOutput SessionDetailExpressionOutput `json:"expression_output,omitempty"`
	Language         string                        `json:"language"`
	Level            string                        `json:"level"`
	ReadingStartedAt float64                       `json:"reading_started_at,omitempty"`

	// SelectedCounts Persisted SelectedItems counts; background items are not currently stored.
	SelectedCounts SelectedItemCounts       `json:"selected_counts"`
	SessionId      string                   `json:"session_id"`
	SessionType    SessionDetailSessionType `json:"session_type"`
	StageSummary   StageSummary             `json:"stage_summary"`
	Stages         []GenerationStageRecord  `json:"stages"`
	Status         SessionDetailStatus      `json:"status"`

	// StoryId present once story generation has persisted a story
	StoryId         string       `json:"story_id,omitempty"`
	Tasks           TaskProgress `json:"tasks"`
	Topic           string       `json:"topic,omitempty"`
	UserExpressions []string     `json:"user_expressions,omitempty"`
}

// SessionDetailContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
type SessionDetailContentType string

// SessionDetailExpressionOutput defines model for SessionDetail.ExpressionOutput.
type SessionDetailExpressionOutput string

// SessionDetailSessionType defines model for SessionDetail.SessionType.
type SessionDetailSessionType string

// SessionDetailStatus defines model for SessionDetail.Status.
type SessionDetailStatus string

// SessionList defines model for SessionList.
type SessionList struct {
	HasMore  bool              `json:"has_more"`
	Limit    int               `json:"limit"`
	Offset   int               `json:"offset"`
	Sessions []SessionOverview `json:"sessions"`
}

// SessionOverview One home/resume row for the current user.
type SessionOverview struct {
	ArchivedAt  float64 `json:"archived_at,omitempty"`
	CompletedAt float64 `json:"completed_at,omitempty"`

	// ContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
	ContentType      SessionOverviewContentType      `json:"content_type"`
	CreatedAt        float64                         `json:"created_at"`
	ExpressionOutput SessionOverviewExpressionOutput `json:"expression_output,omitempty"`
	Language         string                          `json:"language"`
	Level            string                          `json:"level"`
	ReadingStartedAt float64                         `json:"reading_started_at,omitempty"`

	// SelectedCounts Persisted SelectedItems counts; background items are not currently stored.
	SelectedCounts SelectedItemCounts         `json:"selected_counts"`
	SessionId      string                     `json:"session_id"`
	SessionType    SessionOverviewSessionType `json:"session_type"`
	Status         SessionOverviewStatus      `json:"status"`

	// StoryId present once story generation has persisted a story
	StoryId         string       `json:"story_id,omitempty"`
	Tasks           TaskProgress `json:"tasks"`
	Topic           string       `json:"topic,omitempty"`
	UserExpressions []string     `json:"user_expressions,omitempty"`
}

// SessionOverviewContentType what the session's content is — a narrative story or a phrase set. Derived from the session shape (expression-guided + expression_output phrases is a phrase set; everything else is a story). Tells the client whether to load /stories/{id} or the phrase set via /sessions/{id}/content.
type SessionOverviewContentType string

// SessionOverviewExpressionOutput defines model for SessionOverview.ExpressionOutput.
type SessionOverviewExpressionOutput string

// SessionOverviewSessionType defines model for SessionOverview.SessionType.
type SessionOverviewSessionType string

// SessionOverviewStatus defines model for SessionOverview.Status.
type SessionOverviewStatus string

// SessionRef defines model for SessionRef.
type SessionRef struct {
	SessionId string `json:"session_id"`
	Status    string `json:"status"`
}

// SessionTasks defines model for SessionTasks.
type SessionTasks struct {
	// Completed number of tasks already graded
	Completed int    `json:"completed"`
	SessionId string `json:"session_id"`
	Tasks     []Task `json:"tasks"`
	Total     int    `json:"total"`
}

// SkillCategory defines model for SkillCategory.
type SkillCategory struct {
	Id     string          `json:"id"`
	Skills []SkillProgress `json:"skills"`
	Title  string          `json:"title"`
}

// SkillProgress defines model for SkillProgress.
type SkillProgress struct {
	Category       string  `json:"category"`
	Description    string  `json:"description"`
	LastVerifiedAt float64 `json:"last_verified_at,omitempty"`
	Name           string  `json:"name"`

	// PendingVerification True when XP has crossed a tier boundary and AI verification has not completed.
	PendingVerification bool `json:"pending_verification"`

	// ProgressRatio Progress through the current tier as a 0..1 ratio.
	ProgressRatio float64 `json:"progress_ratio"`

	// RecentlyPromoted True shortly after a verified tier promotion.
	RecentlyPromoted bool   `json:"recently_promoted"`
	SkillId          string `json:"skill_id"`
	Tier             int    `json:"tier"`
	TierCount        int    `json:"tier_count"`

	// TierLabel Display label for the current tier, e.g. Not started, Introduced, Practicing, Acquired.
	TierLabel string  `json:"tier_label"`
	UpdatedAt float64 `json:"updated_at,omitempty"`
	Xp        int     `json:"xp"`
	XpPerTier int     `json:"xp_per_tier"`

	// XpToNext XP remaining before the next tier threshold; 0 at the max tier.
	XpToNext int `json:"xp_to_next"`
}

// SkillTree defines model for SkillTree.
type SkillTree struct {
	Categories []SkillCategory `json:"categories"`

	// Language Language code the skill tree is scoped to.
	Language string `json:"language"`
}

// SkillXPDelta defines model for SkillXPDelta.
type SkillXPDelta struct {
	// PendingVerify True when the skill crossed a tier threshold and awaits verification.
	PendingVerify bool   `json:"pending_verify"`
	SkillId       string `json:"skill_id"`
	TierAfter     int    `json:"tier_after"`
	TierBefore    int    `json:"tier_before"`
	XpAfter       int    `json:"xp_after"`
	XpBefore      int    `json:"xp_before"`
	XpDelta       int    `json:"xp_delta"`
}

// StageSummary defines model for StageSummary.
type StageSummary struct {
	ActiveStage string `json:"active_stage,omitempty"`
	Complete    int    `json:"complete"`
	Failed      int    `json:"failed"`
	FailedStage string `json:"failed_stage,omitempty"`
	InProgress  int    `json:"in_progress"`
	Pending     int    `json:"pending"`
	Total       int    `json:"total"`
}

// StoryContentRef Reference to a story session's story; load it via GET /stories/{id}.
type StoryContentRef struct {
	Language string `json:"language"`
	StoryId  string `json:"story_id"`
}

// StoryLoad Everything the reader needs at load time, in one response.
type StoryLoad struct {
	// Knowledge canonical key → canonical knowledge state; unseen items are absent
	Knowledge map[string]ReaderKnowledge `json:"knowledge"`
	Language  string                     `json:"language"`

	// Sentences Authoritative sentence spans for highlighting and sentence breakdown requests.
	Sentences []SentenceSpan `json:"sentences"`
	StoryId   string         `json:"story_id"`

	// SurfaceKnowledge StoryToken.form_key → exact-form level; unseen forms are absent
	SurfaceKnowledge map[string]ReaderSurfaceKnowledge `json:"surface_knowledge"`
	Tokens           []StoryToken                      `json:"tokens"`
}

// StoryToken One token of the server-tokenized story; non-word tokens carry no key.
type StoryToken struct {
	// FormKey opaque key used to look up this form in surface_knowledge
	FormKey string `json:"form_key,omitempty"`
	IsWord  bool   `json:"is_word"`

	// Key canonical knowledge key; omitted for non-word tokens
	Key string `json:"key,omitempty"`

	// Position 0-indexed, stable identifier
	Position int `json:"position"`

	// Surface display form incl. punctuation
	Surface string `json:"surface"`

	// SurfaceKey language-owned exact-form rating key; omitted for non-word tokens
	SurfaceKey string `json:"surface_key,omitempty"`
}

// SubmitTaskRequest defines model for SubmitTaskRequest.
type SubmitTaskRequest struct {
	// InputMethod property of the response; only "typed" supported today
	InputMethod SubmitTaskRequestInputMethod `json:"input_method,omitempty"`

	// Response type-specific response JSON (e.g. {selected_index}, {answer}, {text})
	Response map[string]interface{} `json:"response"`
}

// SubmitTaskRequestInputMethod property of the response; only "typed" supported today
type SubmitTaskRequestInputMethod string

// SubmitTaskResponse defines model for SubmitTaskResponse.
type SubmitTaskResponse struct {
	// AttemptCount How many times this task has been submitted (1 = first submission).
	AttemptCount int `json:"attempt_count"`

	// Grade The outcome of grading one task response.
	Grade Grade `json:"grade"`

	// SkillXp Skill XP deltas persisted for this accepted grade.
	SkillXp []SkillXPDelta `json:"skill_xp"`
	TaskId  string         `json:"task_id"`
}

// Task One task in presentation form (answer-free content + grade once submitted).
type Task struct {
	// Content Present-filtered content — never includes answer keys.
	Content map[string]interface{} `json:"content"`
	Grade   *Grade                 `json:"grade,omitempty"`
	Graded  bool                   `json:"graded"`
	TaskId  string                 `json:"task_id"`

	// TaskType registered TaskType id
	TaskType string `json:"task_type"`
}

// TaskProgress defines model for TaskProgress.
type TaskProgress struct {
	// Completed number of tasks already graded
	Completed int `json:"completed"`
	Pending   int `json:"pending"`
	Total     int `json:"total"`
}

// User defines model for User.
type User struct {
	CreatedAt float64 `json:"created_at"`
	Email     string  `json:"email"`
	LastLogin float64 `json:"last_login,omitempty"`
	UserId    string  `json:"user_id"`
}

// WordKnowledgeRequest defines model for WordKnowledgeRequest.
type WordKnowledgeRequest struct {
	Language string `json:"language"`

	// Level '' clears to unseen
	Level WordKnowledgeRequestLevel `json:"level"`
}

// WordKnowledgeRequestLevel ” clears to unseen
type WordKnowledgeRequestLevel string

// SessionID defines model for SessionID.
type SessionID = string

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// DeleteDictionaryEntryParams defines parameters for DeleteDictionaryEntry.
type DeleteDictionaryEntryParams struct {
	Language string `form:"language" json:"language"`

	// Key canonical knowledge key
	Key string `form:"key" json:"key"`
}

// GetDictionaryEntryParams defines parameters for GetDictionaryEntry.
type GetDictionaryEntryParams struct {
	Language string `form:"language" json:"language"`

	// Key canonical knowledge key
	Key string `form:"key" json:"key"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	Limit    int  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   int  `form:"offset,omitempty" json:"offset,omitempty"`
	Archived bool `form:"archived,omitempty" json:"archived,omitempty"`
}

// ListSkillsParams defines parameters for ListSkills.
type ListSkillsParams struct {
	// Language Optional enabled language code; defaults to profile.active_language.
	Language string `form:"language,omitempty" json:"language,omitempty"`
}

// GetDefinitionParams defines parameters for GetDefinition.
type GetDefinitionParams struct {
	// Key canonical knowledge key to define
	Key string `form:"key" json:"key"`
}

// PostSentenceBreakdownJSONBody defines parameters for PostSentenceBreakdown.
type PostSentenceBreakdownJSONBody struct {
	Position int `json:"position"`
}

// PostWordBreakdownJSONBody defines parameters for PostWordBreakdown.
type PostWordBreakdownJSONBody struct {
	Key string `json:"key"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Credentials

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = Credentials

// PutDictionaryEntryJSONRequestBody defines body for PutDictionaryEntry for application/json ContentType.
type PutDictionaryEntryJSONRequestBody = DictionaryEntryRequest

// PatchProfileJSONRequestBody defines body for PatchProfile for application/json ContentType.
type PatchProfileJSONRequestBody = ProfilePatch

// PostReaderEventsJSONRequestBody defines body for PostReaderEvents for application/json ContentType.
type PostReaderEventsJSONRequestBody = ReaderEventsRequest

// PutReaderSurfaceKnowledgeJSONRequestBody defines body for PutReaderSurfaceKnowledge for application/json ContentType.
type PutReaderSurfaceKnowledgeJSONRequestBody = ReaderSurfaceKnowledgeRequest

// GenerateSessionJSONRequestBody defines body for GenerateSession for application/json ContentType.
type GenerateSessionJSONRequestBody = GenerateRequest

// ImportStoryJSONRequestBody defines body for ImportStory for application/json ContentType.
type ImportStoryJSONRequestBody = ImportStoryRequest

// ImportStoryMultipartRequestBody defines body for ImportStory for multipart/form-data ContentType.
type ImportStoryMultipartRequestBody = ImportStoryUploadRequest

// PostSentenceBreakdownJSONRequestBody defines body for PostSentenceBreakdown for application/json ContentType.
type PostSentenceBreakdownJSONRequestBody PostSentenceBreakdownJSONBody

// PostWordBreakdownJSONRequestBody defines body for PostWordBreakdown for application/json ContentType.
type PostWordBreakdownJSONRequestBody PostWordBreakdownJSONBody

// SubmitTaskJSONRequestBody defines body for SubmitTask for application/json ContentType.
type SubmitTaskJSONRequestBody = SubmitTaskRequest

// PutWordKnowledgeJSONRequestBody defines body for PutWordKnowledge for application/json ContentType.
type PutWordKnowledgeJSONRequestBody = WordKnowledgeRequest
