/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness ping */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enabled language plugins */
        get: operations["listLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register and immediately authenticate a user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh cookie and issue a new access token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every refresh session for the current user */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current user's profile and client preferences
         * @description Returns the typed product profile used for default session generation and UI bootstrapping. In local/no-auth mode this is the synthetic `local` user's profile. Missing fields are defaulted server-side.
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partially update the current user's profile
         * @description Updates typed profile fields and shallow-merges the `preferences` object into the existing arbitrary client-preferences map. A preference value of `null` deletes that key. Unknown top-level fields are rejected so product state stays explicit; client-owned arbitrary values belong under `preferences`.
         */
        patch: operations["patchProfile"];
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current user's skill tree for a language
         * @description Returns every skill defined for the requested language, grouped by category and left-joined with the current user's XP/tier progress. Untouched skills are included with tier 0 and 0 XP so the client can render the complete read-only competency map. If `language` is omitted, the current profile's active_language is used.
         */
        get: operations["listSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sessions for the current user
         * @description Newest-first session overview page for home/resume screens. Includes generation status, story_id when available, selected target/new counts, and compact task progress counts without opening the SSE stream or fetching task bodies.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start generating a session (story + tasks)
         * @description Creates a session and kicks off the staged generation pipeline asynchronously, returning immediately. If language is omitted, the current profile's active_language is used. If level is omitted, the server derives it from verified skill tiers when the language provides deterministic level rules; otherwise the current profile level is used. Poll progress via /sessions/{id}/events. Returns 503 if no LLM gateway is configured.
         */
        post: operations["generateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session detail and persisted generation progress
         * @description Returns one tenant-scoped session with the metadata needed to navigate to reader/tasks, retry failed generation, or render a progress screen without subscribing to SSE. Another user's session returns 404.
         */
        get: operations["getSessionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream generation progress (SSE)
         * @description Server-Sent Events stream of stage transitions. On connect the current persisted stage state is replayed, then live events follow until a terminal `{"stage":"done"}` event. The terminal event is enriched from persisted session detail so late subscribers receive the same navigation fields as live subscribers: final status, session_id, story_id when ready, compact task progress, stage summary, and failed stage/error code when generation failed. token_rate is an approximate upstream tokens/second during story generation (a ticker animation); story text is never streamed.
         */
        get: operations["sessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a failed generation from its failed stage
         * @description Resumes generation using session_generation_stages: a full re-run if the story never completed, or only the failed task-type stages otherwise.
         */
        post: operations["retrySession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load a story for the reader (tokens + knowledge in one call)
         * @description Returns the server-tokenized story plus the caller's per-item knowledge map (canonical key → level + lookup_count) for the story's language, in a single response — everything the reader needs at load time. Words the user has never interacted with are absent from the map and treated as unseen. Stories are user-scoped; another user's story returns 404.
         */
        get: operations["getStory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a word definition for the reader popup
         * @description Walks the resolution chain for one word key: per-story glossary → knowledge_items.metadata → global shared cache → live (Wiktionary, then LLM). A live result is written to the shared cache so the next learner gets it free. Returns 503 if a live LLM lookup is needed but no gateway is configured.
         */
        get: operations["getDefinition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/sentence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sentence breakdown for the sentence containing a position
         * @description Returns the LLM-backed breakdown of the sentence containing the given token position, served from a global cache keyed by the hash of the normalized sentence (so the same sentence in any story reuses it). The response body is the breakdown JSON (shape owned by the prompt builder).
         */
        post: operations["postSentenceBreakdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/word": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deep morphological/etymological breakdown of a word
         * @description Returns the LLM-backed deep breakdown of a word, served from a global cache keyed by the canonical word key. The response body is the breakdown JSON (shape owned by the prompt builder).
         */
        post: operations["postWordBreakdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reader/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a flushed batch of reader events
         * @description Appends a batch of behavioural events to the durable log (idempotent on event_id) and derives knowledge signals from the newly-stored ones — lookup_count, the per-item level (from rate events), and story exposure / context variety (counted once per first read). The caller's identity is authoritative; the payload carries no user_id.
         */
        post: operations["postReaderEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/word_knowledge/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Optimistic knowledge-rating write for one word key
         * @description Sets the learner's level for the word whose canonical key is {token}. Fire-and-forget from the client (the reader updates local state instantly); the response is a bare 204. Idempotent — safe to race a later rate event in a flushed batch.
         */
        put: operations["putWordKnowledge"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a session's tasks to present (answer-free)
         * @description Returns every task for the session in presentation form — content runs through the task type's Present view, so answer keys (correct_index, acceptable_forms) and internal item ids never reach the client — plus a completed/total progress count. The session is tenant-scoped; another user's session is a 404. A task already submitted carries its grade.
         */
        get: operations["getSessionTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one task to present (answer-free)
         * @description Returns one task in presentation form (Present-filtered content plus the grade once submitted), scoped to the owning user. Another user's task is a 404.
         */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a response, grade it, update the learning signal
         * @description Grades the submitted response, persists it, and folds the outcome into user_knowledge (task_total for every targeted item, task_correct for the demonstrated ones), then applies skill XP changes for associated target skills. Rule-graded types (comprehension_mc, fill_blank) grade in-process with no model call; LLM-graded types (production) route through the gateway and return 503 when no gateway is configured. input_method is a property of the response — only "typed" is supported today (scan/audio later). A task that already carries a grade is rejected with 409; re-submission to improve a grade is future work.
         */
        post: operations["submitTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        Language: {
            code: string;
            name: string;
            /** @enum {string} */
            key_strategy: "surface" | "lemma" | "root" | "stem";
            enabled: boolean;
        };
        Credentials: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            user_id: string;
            /** Format: email */
            email: string;
            created_at: number;
            last_login?: number;
        };
        AuthResponse: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /** @constant */
            expires_in: 900;
            user: components["schemas"]["User"];
        };
        GenerateRequest: {
            /** @description registered enabled language code, e.g. 'el'; defaults to profile.active_language */
            language?: string;
            /** @description beginner|elementary|intermediate|upper-intermediate|advanced; defaults to derived verified skill level when available, otherwise profile.level */
            level?: string;
            /** @enum {string} */
            session_type?: "system" | "topic_guided" | "expression_guided";
            /** @description topic_guided only */
            topic?: string;
            /** @description expression_guided only */
            user_expressions?: string[];
            /**
             * @description expression_guided only
             * @enum {string}
             */
            expression_output?: "phrases" | "story";
        };
        Profile: {
            user_id: string;
            /** @description enabled language code used when generation omits language */
            active_language: string;
            /**
             * @description stored level fallback; session generation may derive a fresher value from verified skill tiers
             * @enum {string}
             */
            level: "beginner" | "elementary" | "intermediate" | "upper-intermediate" | "advanced";
            /** @description BCP-47 style UI/gloss language tag, e.g. 'en' */
            ui_language: string;
            /** @description theme id, e.g. 'default' or 'high-contrast' */
            theme: string;
            /** @description arbitrary client-owned preferences; product-critical fields remain top-level */
            preferences: {
                [key: string]: unknown;
            };
        };
        ProfilePatch: {
            /** @description must name an enabled language */
            active_language?: string;
            /**
             * @description stored level fallback; clients should not treat this as arbitrary preference state
             * @enum {string}
             */
            level?: "beginner" | "elementary" | "intermediate" | "upper-intermediate" | "advanced";
            /** @description BCP-47 style UI/gloss language tag */
            ui_language?: string;
            /** @description letters, numbers, '_' and '-' only */
            theme?: string;
            /** @description shallow-merged; null values delete keys */
            preferences?: {
                [key: string]: unknown;
            };
        };
        SkillTree: {
            /** @description Language code the skill tree is scoped to. */
            language: string;
            categories: components["schemas"]["SkillCategory"][];
        };
        SkillCategory: {
            id: string;
            title: string;
            skills: components["schemas"]["SkillProgress"][];
        };
        SkillProgress: {
            skill_id: string;
            name: string;
            description: string;
            category: string;
            tier: number;
            tier_count: number;
            /** @description Display label for the current tier, e.g. Not started, Introduced, Practicing, Acquired. */
            tier_label: string;
            xp: number;
            xp_per_tier: number;
            /** @description XP remaining before the next tier threshold; 0 at the max tier. */
            xp_to_next: number;
            /** @description Progress through the current tier as a 0..1 ratio. */
            progress_ratio: number;
            /** @description True when XP has crossed a tier boundary and AI verification has not completed. */
            pending_verification: boolean;
            /** @description True shortly after a verified tier promotion. */
            recently_promoted: boolean;
            last_verified_at?: number;
            updated_at?: number;
        };
        SessionRef: {
            session_id: string;
            status: string;
        };
        /** @description Persisted SelectedItems counts; background items are not currently stored. */
        SelectedItemCounts: {
            targets: number;
            new: number;
        };
        TaskProgress: {
            total: number;
            /** @description number of tasks already graded */
            completed: number;
            pending: number;
        };
        /** @description One home/resume row for the current user. */
        SessionOverview: {
            session_id: string;
            /** @description present once story generation has persisted a story */
            story_id?: string;
            language: string;
            level: string;
            /** @enum {string} */
            session_type: "system" | "topic_guided" | "expression_guided";
            topic?: string;
            user_expressions?: string[];
            /** @enum {string} */
            expression_output?: "phrases" | "story";
            /** @enum {string} */
            status: "pending" | "generating" | "ready" | "reading" | "complete" | "failed";
            created_at: number;
            reading_started_at?: number;
            completed_at?: number;
            selected_counts: components["schemas"]["SelectedItemCounts"];
            tasks: components["schemas"]["TaskProgress"];
        };
        SessionList: {
            sessions: components["schemas"]["SessionOverview"][];
            limit: number;
            offset: number;
            has_more: boolean;
        };
        StageSummary: {
            total: number;
            pending: number;
            in_progress: number;
            complete: number;
            failed: number;
            active_stage?: string;
            failed_stage?: string;
        };
        GenerationStageRecord: {
            stage: string;
            /** @enum {string} */
            status: "pending" | "in_progress" | "complete" | "failed";
            started_at?: number;
            completed_at?: number;
            error_code?: string;
            error_detail?: string;
            retry_count: number;
        };
        SessionDetail: components["schemas"]["SessionOverview"] & {
            stage_summary: components["schemas"]["StageSummary"];
            stages: components["schemas"]["GenerationStageRecord"][];
        };
        /** @description One SSE progress message (the JSON in each data line). Non-terminal events report a pipeline stage status. The terminal `stage: done` event reports the final session status plus enough persisted state for the client to navigate to reader/tasks or show retry/error UI without guessing. */
        GenerationEvent: {
            /** @description selection|story_generation|tokenization|task_<type>|done */
            stage: string;
            /**
             * @description stage status for progress events; final session status for stage=done
             * @enum {string}
             */
            status?: "pending" | "in_progress" | "complete" | "failed" | "generating" | "ready" | "reading";
            /** @description present on stage=done */
            session_id?: string;
            /** @description present on stage=done once a story has been persisted */
            story_id?: string;
            /** @description approx upstream tokens/sec */
            token_rate?: number;
            /** @description stable code on failed progress events and failed terminal events */
            error_code?: string;
            /** @description first failed stage, present on failed terminal events */
            failed_stage?: string;
            tasks?: components["schemas"]["TaskProgress"];
            stage_summary?: components["schemas"]["StageSummary"];
        };
        /** @description One token of the server-tokenized story; non-word tokens carry no key. */
        StoryToken: {
            /** @description 0-indexed, stable identifier */
            position: number;
            /** @description display form incl. punctuation */
            surface: string;
            /** @description canonical knowledge key; omitted for non-word tokens */
            key?: string;
            is_word: boolean;
        };
        /** @description The reader's per-item view, keyed by canonical key. */
        ReaderKnowledge: {
            /**
             * @description learner self-rating; '' (omitted)=unseen
             * @enum {string}
             */
            level: "" | "1" | "2" | "3" | "4" | "5" | "well_known" | "ignored";
            lookup_count: number;
        };
        /** @description Everything the reader needs at load time, in one response. */
        StoryLoad: {
            story_id: string;
            language: string;
            tokens: components["schemas"]["StoryToken"][];
            /** @description canonical key → knowledge state; unseen items are absent */
            knowledge: {
                [key: string]: components["schemas"]["ReaderKnowledge"];
            };
        };
        /** @description One logged reader interaction. */
        ReaderEvent: {
            /** @description client idempotency key; generated if omitted */
            event_id?: string;
            story_id: string;
            session_id?: string;
            /** @enum {string} */
            event_type: "lookup" | "rate" | "navigate" | "sentence_break";
            /** @description story token position the event is about */
            position?: number;
            /** @description rate only: "1".."5" | "w" | "i" */
            value?: string;
            /** @description Unix seconds (client clock) */
            occurred_at?: number;
        };
        ReaderEventsRequest: {
            events: components["schemas"]["ReaderEvent"][];
        };
        WordKnowledgeRequest: {
            language: string;
            /**
             * @description '' clears to unseen
             * @enum {string}
             */
            level: "" | "1" | "2" | "3" | "4" | "5" | "well_known" | "ignored";
        };
        /** @description A resolved word definition for the reader popup. */
        Definition: {
            key: string;
            /**
             * @description where the definition came from
             * @enum {string}
             */
            source: "glossary" | "metadata" | "wiktionary" | "llm";
            gloss: string;
            grammatical_note?: string;
            example?: string;
            etymology?: string;
        };
        /** @description The outcome of grading one task response. */
        Grade: {
            correct: boolean;
            /** @description 0.0..1.0 */
            score: number;
            feedback?: string;
            /** @description knowledge item ids the response demonstrated */
            items_demonstrated?: string[];
            /** @enum {string} */
            graded_by: "rule" | "llm";
        };
        /** @description One task in presentation form (answer-free content + grade once submitted). */
        Task: {
            task_id: string;
            /** @description registered TaskType id */
            task_type: string;
            /** @description Present-filtered content — never includes answer keys. */
            content: {
                [key: string]: unknown;
            };
            graded: boolean;
            grade?: components["schemas"]["Grade"];
        };
        SessionTasks: {
            session_id: string;
            total: number;
            /** @description number of tasks already graded */
            completed: number;
            tasks: components["schemas"]["Task"][];
        };
        SubmitTaskRequest: {
            /** @description type-specific response JSON (e.g. {selected_index}, {answer}, {text}) */
            response: {
                [key: string]: unknown;
            };
            /**
             * @description property of the response; only "typed" supported today
             * @enum {string}
             */
            input_method?: "typed";
        };
        SubmitTaskResponse: {
            task_id: string;
            grade: components["schemas"]["Grade"];
            /** @description Skill XP deltas persisted for this accepted grade. */
            skill_xp: components["schemas"]["SkillXPDelta"][];
        };
        SkillXPDelta: {
            skill_id: string;
            xp_delta: number;
            xp_before: number;
            xp_after: number;
            tier_before: number;
            tier_after: number;
            /** @description True when the skill crossed a tier threshold and awaits verification. */
            pending_verify: boolean;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication failed */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Too many requests */
        TooManyRequests: {
            headers: {
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Upstream failure */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Service unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SessionID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered languages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Account created; rotated refresh credential set as an HttpOnly cookie */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Authenticated; refresh credential set as an HttpOnly cookie */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All refresh sessions revoked */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    patchProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listSkills: {
        parameters: {
            query?: {
                /** @description Optional enabled language code; defaults to profile.active_language. */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTree"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session overview page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    generateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Generation started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSessionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    sessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["GenerationEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    retrySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Story tokens + knowledge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryLoad"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getDefinition: {
        parameters: {
            query: {
                /** @description canonical knowledge key to define */
                key: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Definition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    postSentenceBreakdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    position: number;
                };
            };
        };
        responses: {
            /** @description Sentence breakdown JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    postWordBreakdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    key: string;
                };
            };
        };
        responses: {
            /** @description Word breakdown JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    postReaderEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReaderEventsRequest"];
            };
        };
        responses: {
            /** @description Accepted; reports how many events were newly stored */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ingested: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    putWordKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description canonical knowledge key (lemma/root/stem per language) */
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WordKnowledgeRequest"];
            };
        };
        responses: {
            /** @description Applied */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getSessionTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session tasks + progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionTasks"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presented task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    submitTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTaskRequest"];
            };
        };
        responses: {
            /** @description The grade */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitTaskResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
