package llm

import (
	"fmt"
	"strings"

	"github.com/dleiferives/tifl/internal/domain"
)

// The builders below turn a LearnerCtx (plus, for some, extra per-call inputs
// held as struct fields) into a ready-to-send LLMRequest. Each is a PromptBuilder
// (Kind, Version, Build). System carries stable instructions so the gateway can
// cache it; User carries the session-specific data. Every builder requests JSON.
// See context/prompting-system.md ("The Four Core Builders").

// Temperatures: generative jobs want variety, judgment jobs want determinism.
const (
	storyTemperature = 0.8
	taskTemperature  = 0.6
	gradeTemperature = 0.2
)

// StoryBuilder produces a story that embeds the target items, draws its
// vocabulary from the background pool, and introduces each new item with enough
// surrounding context to infer its meaning. The vocabulary pool is the whole of
// the constraint: the model is told not to reach beyond SelectedItems, which is
// how the comprehensible-input ratio is held. Assets is optional.
type StoryBuilder struct {
	Assets LangAssets
}

func (StoryBuilder) Kind() string    { return "story_generator" }
func (StoryBuilder) Version() string { return "story/v1" }

func (b StoryBuilder) Build(ctx domain.LearnerCtx) LLMRequest {
	var sys strings.Builder
	fmt.Fprintf(&sys, "You are a writer of short %s learning stories.\n", ctx.Language)
	sys.WriteString("Write a single short, coherent story in the target language that a learner can understand.\n")
	sys.WriteString("Hard constraints:\n")
	sys.WriteString("- Use ONLY vocabulary drawn from the provided item lists. Do not freely introduce other vocabulary.\n")
	sys.WriteString("- Every target item must appear, ideally where its meaning is inferable from context.\n")
	sys.WriteString("- Every new item must appear at least once, supported by surrounding context (not dropped in).\n")
	if note := noteOf(b.Assets); note != "" {
		fmt.Fprintf(&sys, "- Writing system: %s\n", note)
	}
	sys.WriteString("Respond with a JSON object: ")
	sys.WriteString(`{"story": string, "estimated_coverage": number, "glossary": [{"key": string, "gloss": string}]}.`)
	sys.WriteString("\nReturn JSON only — no prose, no markdown.")

	var usr strings.Builder
	if constraints := serializeSkillConstraints(ctx.Skills); constraints != "" {
		usr.WriteString("Complexity constraints:\n")
		usr.WriteString(constraints)
	} else {
		fmt.Fprintf(&usr, "Write at the %s level.\n", levelOrDefault(ctx.Level))
	}
	writeItemBlock(&usr, "TARGET items (exercise these with intent)", ctx.Selected.Targets, formatItemTarget)
	writeItemBlock(&usr, "BACKGROUND vocabulary (known; draw from these freely)", ctx.Selected.Background, formatItemCompact)
	writeItemBlock(&usr, "NEW items (introduce each with context support)", ctx.Selected.New, formatItemNew)
	if g := ctx.Guidance; g != nil && g.Topic != "" {
		fmt.Fprintf(&usr, "\nRequested topic: %s\n", g.Topic)
	}
	if avoid := recentTopics(ctx.RecentHistory); avoid != "" {
		fmt.Fprintf(&usr, "\nAvoid repeating these recent topics/settings: %s\n", avoid)
	}
	for i, ex := range examplesOf(b.Assets, ctx.Level) {
		fmt.Fprintf(&usr, "\nExample passage %d (match this level and style):\n%s\n", i+1, ex)
	}

	return LLMRequest{
		System:         sys.String(),
		User:           usr.String(),
		Temperature:    storyTemperature,
		MaxTokens:      1500,
		ResponseFormat: "json",
	}
}

// TaskBuilder produces the content JSON for one task type over an already-written
// story. One call yields one task type; multiple types are generated by parallel
// builders. The task system validates the returned content against the type's
// schema, so this builder does not encode that schema beyond asking for JSON.
type TaskBuilder struct {
	Story      string
	TaskTypeID string
	Assets     LangAssets
}

func (b TaskBuilder) Kind() string  { return "task_" + b.TaskTypeID }
func (TaskBuilder) Version() string { return "task/v1" }

func (b TaskBuilder) Build(ctx domain.LearnerCtx) LLMRequest {
	var sys strings.Builder
	fmt.Fprintf(&sys, "You generate %q tasks for %s learners.\n", b.TaskTypeID, ctx.Language)
	sys.WriteString("Given a story and the items it should exercise, produce the task content as JSON only.\n")
	if note := noteOf(b.Assets); note != "" {
		fmt.Fprintf(&sys, "Writing system: %s\n", note)
	}
	sys.WriteString("Return JSON only — no prose, no markdown.")

	var usr strings.Builder
	fmt.Fprintf(&usr, "Level: %s\n", levelOrDefault(ctx.Level))
	writeItemBlock(&usr, "Exercise these target items", ctx.Selected.Targets, formatItemTarget)
	usr.WriteString("\nStory:\n")
	usr.WriteString(b.Story)
	usr.WriteString("\n")

	return LLMRequest{
		System:         sys.String(),
		User:           usr.String(),
		Temperature:    taskTemperature,
		MaxTokens:      800,
		ResponseFormat: "json",
	}
}

// GraderBuilder grades an open-ended response. It is only invoked for task types
// whose NeedsLLM() is true; determinate types (multiple choice, exact fill-blank)
// are graded by rule in Go without any model call. The grade JSON it requests is
// the minimum every grade carries (see tasks.Grade / GradeResult).
type GraderBuilder struct {
	Story       string
	TaskTypeID  string
	TaskContent map[string]any
	Response    map[string]any
}

func (GraderBuilder) Kind() string    { return "grader" }
func (GraderBuilder) Version() string { return "grader/v1" }

func (b GraderBuilder) Build(ctx domain.LearnerCtx) LLMRequest {
	var sys strings.Builder
	fmt.Fprintf(&sys, "You grade %s learner responses fairly and concisely.\n", ctx.Language)
	sys.WriteString("Judge whether the response demonstrates understanding of the targeted items, ")
	sys.WriteString("distinguishing a demonstrated concept from a merely surface-correct answer.\n")
	sys.WriteString("Respond with a JSON object: ")
	sys.WriteString(`{"correct": bool, "score": number (0..1), "feedback": string, "items_demonstrated": [string]}.`)
	sys.WriteString("\nitems_demonstrated lists the knowledge-item keys the response shows real understanding of.")
	sys.WriteString("\nReturn JSON only — no prose, no markdown.")

	var usr strings.Builder
	writeItemBlock(&usr, "Target items the task exercises", ctx.Selected.Targets, formatItemTarget)
	usr.WriteString("\nStory (context):\n")
	usr.WriteString(b.Story)
	fmt.Fprintf(&usr, "\n\nTask content:\n%s\n", compactJSON(b.TaskContent))
	fmt.Fprintf(&usr, "\nLearner response:\n%s\n", compactJSON(b.Response))

	return LLMRequest{
		System:         sys.String(),
		User:           usr.String(),
		Temperature:    gradeTemperature,
		MaxTokens:      500,
		ResponseFormat: "json",
	}
}

// AssessorBuilder makes a qualitative acquisition judgment for one item the hard
// system cannot resolve algorithmically (conflicting signals — many lookups but
// high exposure, surface recognition without production, etc.). It is not called
// every session; only on the ambiguous cases the selector flags.
type AssessorBuilder struct {
	Item            domain.KnowledgeItem
	Signals         domain.UserKnowledge
	RecentExamples  []string // how the item appeared in recent stories
	ResponseSamples []string // learner task responses involving it
}

func (AssessorBuilder) Kind() string    { return "assessor" }
func (AssessorBuilder) Version() string { return "assessor/v1" }

func (b AssessorBuilder) Build(ctx domain.LearnerCtx) LLMRequest {
	var sys strings.Builder
	fmt.Fprintf(&sys, "You assess whether a %s learner has acquired a single knowledge item.\n", ctx.Language)
	sys.WriteString("Weigh the quantitative signals against the qualitative evidence and make one judgment.\n")
	sys.WriteString("Respond with a JSON object: ")
	sys.WriteString(`{"stage": one of ["recognizing","acquiring","acquired","automatic"], "primary_signal": string, "recommendation": string}.`)
	sys.WriteString("\nReturn JSON only — no prose, no markdown.")

	var usr strings.Builder
	fmt.Fprintf(&usr, "Item: %s (%s)\n", b.Item.Key, b.Item.ItemType)
	if gloss := metaString(b.Item.Metadata, "gloss"); gloss != "" {
		fmt.Fprintf(&usr, "Meaning: %s\n", gloss)
	}
	s := b.Signals
	fmt.Fprintf(&usr, "Signals: exposure=%d context_variety=%d lookups=%d task_correct=%d/%d current_stage=%s\n",
		s.ExposureCount, s.ContextVariety, s.LookupCount, s.TaskCorrect, s.TaskTotal, s.AcquisitionStage)
	writeLines(&usr, "Recent story appearances", b.RecentExamples)
	writeLines(&usr, "Learner response samples", b.ResponseSamples)

	return LLMRequest{
		System:         sys.String(),
		User:           usr.String(),
		Temperature:    gradeTemperature,
		MaxTokens:      400,
		ResponseFormat: "json",
	}
}

// compile-time assertions that every builder satisfies PromptBuilder.
var (
	_ PromptBuilder = StoryBuilder{}
	_ PromptBuilder = TaskBuilder{}
	_ PromptBuilder = GraderBuilder{}
	_ PromptBuilder = AssessorBuilder{}
)
